ALTER TABLE [DSQLT].[Types]
    ADD CONSTRAINT [PK_Types] PRIMARY KEY CLUSTERED ([type_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

