--CREATING MASTER KEY TO ENCRYPT ALL THE CREDENTIALS SECRETS
IF (SELECT COUNT(*) FROM SYS.SYMMETRIC_KEYS WHERE NAME LIKE '%DATABASEMASTERKEY%') = 0
BEGIN

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'S0ME!NFO';

END

--CREATING TABLE USERDETAILS WHERE WE BULK INSERT THE DATA FROM CSV
IF OBJECT_ID('USERDETAILS') IS NULL
BEGIN    
CREATE TABLE USERDETAILS (ID INT,NAME VARCHAR(MAX),AGE INT)
END 