SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[asset].[TestAssetLarge]') AND type in (N'U'))
BEGIN
CREATE TABLE [asset].[TestAssetLarge](
	[DocImageID] [bigint] IDENTITY(1,1) NOT NULL,
	[DocTrackID] [nvarchar](1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Image] [varbinary](max) NULL,
	[ContentType] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[filename] [nvarchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[DocImageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
