SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dimension].[Country]') AND type in (N'U'))
BEGIN
CREATE TABLE [dimension].[Country](
	[CountryID] [smallint] IDENTITY(1,1) NOT NULL,
	[UN_Code] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ISO_Code2] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ISO_Code3] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CountryName] [varchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CountryDomain] [varchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[StartDT] [datetime2](7) GENERATED ALWAYS AS ROW START NOT NULL,
	[EndDT] [datetime2](7) GENERATED ALWAYS AS ROW END NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CountryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
	PERIOD FOR SYSTEM_TIME ([StartDT], [EndDT])
) ON [PRIMARY]
WITH
(
SYSTEM_VERSIONING = ON ( HISTORY_TABLE = [dimension].[Country_History] )
)
END
GO
