SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [lnd].[EKKO_purchasing_doc_header](
	[MANDT] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EBELN] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BUKRS] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BSTYP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BSART] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BSAKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOEKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATU] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AEDAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ERNAM] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LASTCHANGEDATETIME] [numeric](27, 7) NULL,
	[PINCR] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LPONR] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LIFNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPRAS] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZTERM] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZBD1T] [numeric](3, 0) NULL,
	[ZBD2T] [numeric](3, 0) NULL,
	[ZBD3T] [numeric](3, 0) NULL,
	[ZBD1P] [numeric](6, 3) NULL,
	[ZBD2P] [numeric](6, 3) NULL,
	[EKORG] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EKGRP] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WAERS] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WKURS] [numeric](12, 5) NULL,
	[KUFIX] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BEDAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KDATB] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KDATE] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BWBDT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ANGDT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BNDDT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GWLDT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUSNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ANGNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IHRAN] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IHREZ] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VERKF] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TELF1] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LLIEF] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KUNNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KONNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ABGRU] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUTLF] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WEAKT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RESWK] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LBLIF] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INCO1] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INCO2] [nvarchar](28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KTWRT] [numeric](20, 2) NULL,
	[SUBMI] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KNUMV] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KALSM] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STAFO] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LIFRE] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXNUM] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UNSEZ] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOGSY] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPINC] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STAKO] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FRGGR] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FRGSX] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FRGKE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FRGZU] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FRGRL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LANDS] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LPHIS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADRNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STCEG_L] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STCEG] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ABSGR] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KORNR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MEMORY] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PROCSTAT] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RLWRT] [numeric](20, 2) NULL,
	[REVNO] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCMPROC] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REASON_CODE] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MEMORYTYPE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RETTP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RETPC] [numeric](6, 2) NULL,
	[DPTYP] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DPPCT] [numeric](6, 2) NULL,
	[DPAMT] [numeric](14, 2) NULL,
	[DPDAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MSR_ID] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HIERARCHY_EXISTS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[THRESHOLD_EXISTS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LEGAL_CONTRACT] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DESCRIPTION] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RELEASE_DATE] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VSART] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HANDOVERLOC] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHIPCOND] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INCOV] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INCO2_L] [nvarchar](70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INCO3_L] [nvarchar](70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GRWCU] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INTRA_REL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INTRA_EXCL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QTN_ERLST_SUBMSN_DATE] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FOLLOWON_DOC_CAT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FOLLOWON_DOC_TYPE] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DUMMY_EKKO_INCL_EEW_PS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXTERNALSYSTEM] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXTERNALREFERENCEID] [nvarchar](70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXT_REV_TMSTMP] [numeric](27, 7) NULL,
	[ISEOPBLOCKED] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ISAGED] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FORCE_ID] [nvarchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FORCE_CNT] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RELOC_ID] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RELOC_SEQ_ID] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SOURCE_LOGSYS] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_TRANSACTION] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_ITEM_GROUP] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_VAS_LAST_ITEM] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_OS_STG_CHANGE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIEXGNUM] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIEXGTYP] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIAEVGTYPE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIPIPEVAL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_LIFNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_DCITYC] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_DCOUNC] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_DREGIO] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_DLAND1] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_OCITYC] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_OCOUNC] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_OREGIO] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_OLAND1] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_PORGIN] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_PDESTN] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_PTRIP] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_PBATCH] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_MOT] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_AORGIN] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_ADESTN] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_TRUCKN] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIA_BASELO] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OID_EXTBOL] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OID_MISCDL] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TMS_REF_UUID] [nvarchar](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZDUMMY] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZDATA1] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZDATA2] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZDATA3] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZDATA4] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZAPCGK] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[APCGK_EXTEND] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZBAS_DATE] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZADATTYP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZSTART_DAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Z_DEV] [numeric](7, 3) NULL,
	[ZINDANX] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZLIMIT_DAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NUMERATOR] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HASHCAL_BDAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HASHCAL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NEGATIVE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HASHCAL_EXISTS] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KNOWN_INDEX] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POSTAT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VZSKZ] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_SNST_STATUS] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PROCE] [nvarchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONC] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONT] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMP] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OUTR] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DESP] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DESP_DAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DESP_CARGO] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PARE] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PARE_DAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PARE_CARGO] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PFM_CONTRACT] [nvarchar](24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POHF_TYPE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EQ_EINDT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EQ_WERKS] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIXPO] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EKGRP_ALLOW] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WERKS_ALLOW] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONTRACT_ALLOW] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PSTYP_ALLOW] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIXPO_ALLOW] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KEY_ID_ALLOW] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUREL_ALLOW] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DELPER_ALLOW] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EINDT_ALLOW] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LTSNR_ALLOW] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTB_LEVEL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTB_COND_TYPE] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KEY_ID] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTB_VALUE] [numeric](23, 2) NULL,
	[OTB_CURR] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTB_RES_VALUE] [numeric](22, 2) NULL,
	[OTB_SPEC_VALUE] [numeric](22, 2) NULL,
	[SPR_RSN_PROFILE] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BUDG_TYPE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTB_STATUS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTB_REASON] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CHECK_TYPE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CON_OTB_REQ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CON_PREBOOK_LEV] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CON_DISTR_LEV] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
