SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [lnd].[MARC_plant_data_for_material](
	[MANDT] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MATNR] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WERKS] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PSTAT] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LVORM] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BWTTY] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[XCHAR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MMSTA] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MMSTD] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAABC] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZKRI] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EKGRP] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUSME] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISPR] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISMM] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISPO] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZDIE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PLIFZ] [numeric](3, 0) NULL,
	[WEBAZ] [numeric](3, 0) NULL,
	[PERKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUSSS] [numeric](6, 2) NULL,
	[DISLS] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BESKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SOBSL] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MINBE] [numeric](17, 3) NULL,
	[EISBE] [numeric](17, 3) NULL,
	[BSTMI] [numeric](17, 3) NULL,
	[BSTMA] [numeric](17, 3) NULL,
	[BSTFE] [numeric](17, 3) NULL,
	[BSTRF] [numeric](17, 3) NULL,
	[MABST] [numeric](17, 3) NULL,
	[LOSFX] [numeric](14, 2) NULL,
	[SBDKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LAGPR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ALTSL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZAUS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUSDT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NFMAT] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZBED] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MISKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FHORI] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PFREI] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FFREI] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RGEKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FEVOR] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BEARZ] [numeric](6, 2) NULL,
	[RUEZT] [numeric](6, 2) NULL,
	[TRANZ] [numeric](6, 2) NULL,
	[BASMG] [numeric](17, 3) NULL,
	[DZEIT] [numeric](3, 0) NULL,
	[MAXLZ] [numeric](6, 0) NULL,
	[LZEIH] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZPRO] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GPMKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UEETO] [numeric](4, 1) NULL,
	[UEETK] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UNETO] [numeric](4, 1) NULL,
	[WZEIT] [numeric](3, 0) NULL,
	[ATPKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VZUSL] [numeric](6, 2) NULL,
	[HERBL] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INSMK] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPROZ] [numeric](4, 1) NULL,
	[QUAZT] [numeric](3, 0) NULL,
	[SSQSS] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MPDAU] [numeric](6, 0) NULL,
	[KZPPV] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZDKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WSTGH] [numeric](11, 0) NULL,
	[PRFRQ] [numeric](6, 0) NULL,
	[NKMPR] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UMLMC] [numeric](18, 3) NULL,
	[LADGR] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[XCHPF] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[USEQU] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LGRAD] [numeric](4, 1) NULL,
	[AUFTL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PLVAR] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTYPE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OBJID] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MTVFP] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PERIV] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZKFK] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VRVEZ] [numeric](6, 2) NULL,
	[VBAMG] [numeric](17, 3) NULL,
	[VBEAZ] [numeric](6, 2) NULL,
	[LIZYK] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BWSCL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KAUTB] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KORDB] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STAWN] [nvarchar](17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HERKL] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HERKR] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXPME] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MTVER] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRCTR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TRAME] [numeric](18, 3) NULL,
	[MRPPP] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SAUFT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FXHOR] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VRMOD] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VINT1] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VINT2] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VERKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STLAL] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STLAN] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PLNNR] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[APLAL] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOSGR] [numeric](17, 3) NULL,
	[SOBSK] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FRTME] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LGPRO] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISGR] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KAUSF] [numeric](6, 2) NULL,
	[QZGTP] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QMATV] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TAKZT] [numeric](3, 0) NULL,
	[RWPRO] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COPAM] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ABCIN] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AWSLS] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SERNP] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CUOBJ] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STDPD] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SFEPR] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[XMCNG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QSSYS] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LFRHY] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RDPRF] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VRBMT] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VRBWK] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VRBDT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VRBFK] [numeric](5, 2) NULL,
	[AUTRU] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PREFE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRENC] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRENO] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PREND] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRENE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRENG] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ITARK] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SERVG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZKUP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STRGR] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CUOBV] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LGFSB] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCHGT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCFIX] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EPRIO] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QMATA] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RESVP] [numeric](3, 0) NULL,
	[PLNTY] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOMGR] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UMRSL] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ABFAC] [numeric](3, 1) NULL,
	[SFCPF] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHFLG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHZET] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MDACH] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZECH] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MEGRU] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MFRGR] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PROFIL] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VKUMC] [numeric](18, 2) NULL,
	[VKTRW] [numeric](18, 2) NULL,
	[KZAGL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FVIDK] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FXPRU] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOGGR] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FPRFM] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GLGMG] [numeric](18, 3) NULL,
	[VKGLG] [numeric](18, 2) NULL,
	[INDUS] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MOWNR] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MOGRU] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CASNR] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GPNUM] [nvarchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STEUC] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FABKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MATGR] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VSPVB] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DPLFS] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DPLPU] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DPLHO] [numeric](3, 0) NULL,
	[MINLS] [numeric](17, 3) NULL,
	[MAXLS] [numeric](17, 3) NULL,
	[FIXLS] [numeric](17, 3) NULL,
	[LTINC] [numeric](17, 3) NULL,
	[COMPL] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONVT] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHPRO] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AHDIS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIBER] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZPSP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OCMPF] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[APOKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MCRUE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LFMON] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LFGJA] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EISLO] [numeric](17, 3) NULL,
	[NCOST] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ROTATION_DATE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UCHKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UCMAT] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BWESB] [numeric](18, 3) NULL,
	[SGT_COVS] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SGT_STATC] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SGT_SCOPE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SGT_MRPSI] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SGT_PRCM] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SGT_CHINT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SGT_STK_PRT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SGT_DEFSC] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SGT_MRP_ATP_STATUS] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SGT_MMSTD] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_MG_ARUN_REQ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_SEAIM] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_VAR_GROUP] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_KZECH] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_CALENDAR_GROUP] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ARUN_FIX_BATCH] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PPSKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONS_PROCG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GI_PR_TIME] [numeric](3, 0) NULL,
	[MULTIPLE_EKGRP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REF_SCHEMA] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MIN_TROC] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAX_TROC] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TARGET_STOCK] [numeric](17, 3) NULL,
	[NF_FLAG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/CWM/UMLMC] [numeric](18, 3) NULL,
	[/CWM/TRAME] [numeric](18, 3) NULL,
	[/CWM/BWESB] [numeric](18, 3) NULL,
	[SCM_MATLOCID_GUID16] [nvarchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_MATLOCID_GUID22] [nvarchar](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_GRPRT] [numeric](11, 0) NULL,
	[SCM_GIPRT] [numeric](11, 0) NULL,
	[SCM_SCOST] [numeric](17, 3) NULL,
	[SCM_RELDT] [numeric](3, 0) NULL,
	[SCM_RRP_TYPE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_HEUR_ID] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_PACKAGE_ID] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_SSPEN] [numeric](17, 3) NULL,
	[SCM_GET_ALERTS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_RES_NET_NAME] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_CONHAP] [numeric](17, 3) NULL,
	[SCM_HUNIT] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_CONHAP_OUT] [numeric](17, 3) NULL,
	[SCM_HUNIT_OUT] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_SHELF_LIFE_LOC] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_SHELF_LIFE_DUR] [numeric](11, 0) NULL,
	[SCM_MATURITY_DUR] [numeric](11, 0) NULL,
	[SCM_SHLF_LFE_REQ_MIN] [numeric](11, 0) NULL,
	[SCM_SHLF_LFE_REQ_MAX] [numeric](11, 0) NULL,
	[SCM_LSUOM] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_REORD_DUR] [numeric](11, 0) NULL,
	[SCM_TARGET_DUR] [numeric](11, 0) NULL,
	[SCM_TSTRID] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_STRA1] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_PEG_PAST_ALERT] [numeric](11, 0) NULL,
	[SCM_PEG_FUTURE_ALERT] [numeric](11, 0) NULL,
	[SCM_PEG_STRATEGY] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_PEG_WO_ALERT_FST] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_FIXPEG_PROD_SET] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_WHATBOM] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_RRP_SEL_GROUP] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_INTSRC_PROF] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_PRIO] [tinyint] NULL,
	[SCM_MIN_PASS_AMOUNT] [numeric](19, 3) NULL,
	[SCM_PROFID] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_GES_MNG_USE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_GES_BST_USE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DUMMY_PLNT_INCL_EEW_PS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/SAPMP/TOLPRPL] [numeric](4, 1) NULL,
	[/SAPMP/TOLPRMI] [numeric](4, 1) NULL,
	[/STTPEC/SERVALID] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/VSO/R_PKGRP] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/VSO/R_LANE_NUM] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/VSO/R_PAL_VEND] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/VSO/R_FORK_DIR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IUID_RELEVANT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IUID_TYPE] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UID_IEA] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DPCBT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OITAXGRP] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIOILCON] [numeric](6, 2) NULL,
	[OIEDCODE] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FDICH] [float] NULL,
	[COEFF] [float] NULL,
	[ZZ_PLANNER_DP] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_PLANNER_SNP] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_SNP_HORIZON] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_SNPST_HORIZON] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_SNP_FIXING] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_SNP_PRIORITY] [tinyint] NULL,
	[ZZ_SNPST_FIXING] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_SNP_PRD_F] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_SNP_PRD_P] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_RQCOVERFLG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_RQCOVERTYP] [numeric](5, 3) NULL,
	[ZZ_PPDS_HORIZON] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_TARGET_DAY] [numeric](11, 0) NULL,
	[ZZ_KOSCH_LOC_GRP] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_KOSCH_CC] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_ATP_CHMOD] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_SAPAPO_STRAT] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_SAPAPO_BDGRP] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_SAPAPO_CHKHOR] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_MSDPSBMETH] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_GRGI_HCCGR] [numeric](17, 3) NULL,
	[ZZ_GRGI_HCCGI] [numeric](17, 3) NULL,
	[ZZ_GRGI_HCCGR_UN] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_GRGI_HCCGI_UN] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_GRGI_SCBU] [numeric](17, 3) NULL,
	[ZZ_GRGI_SCBU_UN] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_PULL_DPLHO] [numeric](3, 0) NULL,
	[ZZ_PUSH_DPLHO] [numeric](3, 0) NULL,
	[ZZ_DPLPU] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_BESKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_FS_RULE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_PLANNER_PPS] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_PEG_STRATEGY] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_PEGWOALERTFST] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_PEGFUTURE_MAX] [numeric](11, 0) NULL,
	[ZZ_PEG_PAST_MAX] [numeric](11, 0) NULL,
	[ZZ_PEGFUTUREALRT] [numeric](11, 0) NULL,
	[ZZ_PEGPAST_ALERT] [numeric](11, 0) NULL,
	[ZZ_LSUOM] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_TARGET_METHOD] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_RRP_TYPE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_HEUR_ID] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_FRTME] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_WHATBOM] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_SCOST] [numeric](17, 3) NULL,
	[ZZ_NDPEN_SO] [numeric](17, 3) NULL,
	[ZZ_MAXLAT_SO] [numeric](3, 0) NULL,
	[ZZ_DPEN_SO] [numeric](17, 3) NULL,
	[ZZ_NDPEN_FCAST] [numeric](17, 3) NULL,
	[ZZ_MAXLAT_FCAST] [numeric](3, 0) NULL,
	[ZZ_DPEN_FCAST] [numeric](17, 3) NULL,
	[ZZ_SS_PEN_COSTS] [numeric](17, 3) NULL,
	[ZZ_FIXHZ] [numeric](14, 0) NULL,
	[ZZ_PKZPRODH] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_PEGNODYN] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_UPD_BINLOC] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_TYPE_OF_PLANT] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_SPOTS_HORI_M] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_SPOTS_HORI_Q] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_BOAF_EXCLUDE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_SPOTS_THRESD] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_TY_PLANT_OUT] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_STLP_CAT] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_STLP_MATCODE] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_STLP_ATTCODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_STLP_GROUP] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_STLP_DASHB] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_STLP_DMM] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_STLP_COMP] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_STLP_LOCCOMP] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_LGISD] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_FGSRD] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
