SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [lnd].[EKPO_purchasing_doc_item](
	[MANDT] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EBELN] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EBELP] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UNIQUEID] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOEKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATU] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AEDAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TXZ01] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MATNR] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMATN] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BUKRS] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WERKS] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LGORT] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BEDNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MATKL] [nvarchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INFNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDNLF] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KTMNG] [numeric](17, 3) NULL,
	[MENGE] [numeric](17, 3) NULL,
	[MEINS] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BPRME] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BPUMZ] [numeric](6, 0) NULL,
	[BPUMN] [numeric](6, 0) NULL,
	[UMREZ] [numeric](6, 0) NULL,
	[UMREN] [numeric](6, 0) NULL,
	[NETPR] [numeric](14, 2) NULL,
	[PEINH] [numeric](6, 0) NULL,
	[NETWR] [numeric](16, 2) NULL,
	[BRTWR] [numeric](16, 2) NULL,
	[AGDAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WEBAZ] [numeric](3, 0) NULL,
	[MWSKZ] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BONUS] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INSMK] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPINF] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRSDR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCHPR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAHNZ] [numeric](3, 0) NULL,
	[MAHN1] [numeric](4, 0) NULL,
	[MAHN2] [numeric](4, 0) NULL,
	[MAHN3] [numeric](4, 0) NULL,
	[UEBTO] [numeric](4, 1) NULL,
	[UEBTK] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UNTTO] [numeric](4, 1) NULL,
	[BWTAR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BWTTY] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ABSKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AGMEM] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ELIKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EREKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PSTYP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KNTTP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZVBR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VRTKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TWRKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WEPOS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WEUNB] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REPOS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WEBRE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZABS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LABNR] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KONNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KTPNR] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ABDAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ABFTZ] [numeric](17, 3) NULL,
	[ETFZ1] [numeric](3, 0) NULL,
	[ETFZ2] [numeric](3, 0) NULL,
	[KZSTU] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NOTKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LMEIN] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EVERS] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZWERT] [numeric](16, 2) NULL,
	[NAVNW] [numeric](16, 2) NULL,
	[ABMNG] [numeric](17, 3) NULL,
	[PRDAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BSTYP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EFFWR] [numeric](16, 2) NULL,
	[XOBLR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KUNNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADRNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EKKOL] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SKTOF] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STAFO] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PLIFZ] [numeric](3, 0) NULL,
	[NTGEW] [numeric](17, 3) NULL,
	[GEWEI] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TXJCD] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ETDRK] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SOBKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ARSNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ARSPS] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INSNC] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SSQSS] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZGTYP] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EAN11] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BSTAE] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REVLV] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GEBER] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FISTL] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIPOS] [nvarchar](24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KO_GSBER] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KO_PARGB] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KO_PRCTR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KO_PPRCTR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MEPRF] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BRGEW] [numeric](17, 3) NULL,
	[VOLUM] [numeric](17, 3) NULL,
	[VOLEH] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INCO1] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INCO2] [nvarchar](28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VORAB] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KOLIF] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LTSNR] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PACKNO] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FPLNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GNETWR] [numeric](16, 2) NULL,
	[STAPO] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UEBPO] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LEWED] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMLIF] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LBLKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SATNR] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ATTYP] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VSART] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HANDOVERLOC] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KANBA] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADRN2] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CUOBJ] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[XERSY] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EILDT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRDAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRUHR] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRUNR] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AKTNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ABELN] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ABELP] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ANZPU] [numeric](17, 3) NULL,
	[PUNEI] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SAISO] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SAISJ] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EBON2] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EBON3] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EBONF] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MLMAA] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MHDRZ] [numeric](5, 0) NULL,
	[ANFNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ANFPS] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZKFG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[USEQU] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UMSOK] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BANFN] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BNFPO] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MTART] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPTYP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPVOR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZWI1] [numeric](18, 2) NULL,
	[KZWI2] [numeric](18, 2) NULL,
	[KZWI3] [numeric](18, 2) NULL,
	[KZWI4] [numeric](18, 2) NULL,
	[KZWI5] [numeric](18, 2) NULL,
	[KZWI6] [numeric](18, 2) NULL,
	[SIKGR] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MFZHI] [numeric](19, 3) NULL,
	[FFZHI] [numeric](19, 3) NULL,
	[RETPO] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUREL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BSGRU] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LFRET] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MFRGR] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NRFHG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[J_1BNBM] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[J_1BMATUSE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[J_1BMATORG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[J_1BOWNPRO] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[J_1BINDUST] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ABUEB] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NLABD] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NFABD] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZBWS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BONBA] [numeric](18, 2) NULL,
	[FABKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[J_1AINDXP] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[J_1AIDATEP] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MPROF] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EGLKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZTLF] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZFME] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RDPRF] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TECHS] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CHG_SRV] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CHG_FPLNR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MFRPN] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MFRNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMNFR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NOVET] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AFNAM] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TZONRC] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IPRKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LEBRE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BERID] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[XCONDITIONS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[APOMS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCOMP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GRANT_NBR] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FKBER] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATUS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RESLO] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KBLNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KBLPOS] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WEORA] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SRV_BAS_COM] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRIO_URG] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRIO_REQ] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMPST] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIFF_INVOICE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TRMRISK_RELEVANT] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CREATIONDATE] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CREATIONTIME] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPE_ABGRU] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPE_CRM_SO] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPE_CRM_SO_ITEM] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPE_CRM_REF_SO] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPE_CRM_REF_ITEM] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPE_CRM_FKREL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPE_CHNG_SYS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPE_INSMK_SRC] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPE_CQ_CTRLTYPE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPE_CQ_NOCQ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REASON_CODE] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CQU_SAR] [numeric](19, 3) NULL,
	[ANZSN] [int] NULL,
	[SPE_EWM_DTC] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXLIN] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXSNR] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EHTYP] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RETPC] [numeric](6, 2) NULL,
	[DPTYP] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DPPCT] [numeric](6, 2) NULL,
	[DPAMT] [numeric](14, 2) NULL,
	[DPDAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FLS_RSTO] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXT_RFX_NUMBER] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXT_RFX_ITEM] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXT_RFX_SYSTEM] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SRM_CONTRACT_ID] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SRM_CONTRACT_ITM] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BLK_REASON_ID] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BLK_REASON_TXT] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ITCONS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIXMG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WABWE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CMPL_DLV_ITM] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INCO2_L] [nvarchar](70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INCO3_L] [nvarchar](70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STAWN] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ISVCO] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GRWRT] [numeric](14, 2) NULL,
	[SERVICEPERFORMER] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRODUCTTYPE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REQUESTFORQUOTATION] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REQUESTFORQUOTATIONITEM] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXTMATERIALFORPURG] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TARGET_VALUE] [numeric](20, 2) NULL,
	[EXTERNALREFERENCEID] [nvarchar](70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TC_AUT_DET] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MANUAL_TC_REASON] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FISCAL_INCENTIVE] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TAX_SUBJECT_ST] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FISCAL_INCENTIVE_ID] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SF_TXJCD] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DUMMY_EKPO_INCL_EEW_PS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXPECTED_VALUE] [numeric](16, 2) NULL,
	[LIMIT_AMOUNT] [numeric](16, 2) NULL,
	[ENH_DATE1] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENH_DATE2] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENH_PERCENT] [numeric](6, 2) NULL,
	[ENH_NUMC1] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[_DATAAGING] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/BEV1/NEGEN_ITEM] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/BEV1/NEDEPFREE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/BEV1/NESTRUCCAT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADVCODE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BUDGET_PD] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXCPE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FMFGUS_KEY] [nvarchar](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IUID_RELEVANT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MRPIND] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIPIPEVAL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_LIFNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_DCITYC] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_DCOUNC] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_DREGIO] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_DLAND1] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_OCITYC] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_OCOUNC] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_OREGIO] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_OLAND1] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_PORGIN] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_PDESTN] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_PTRIP] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_PBATCH] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_MOT] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_AORGIN] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_ADESTN] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIC_TRUCKN] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIA_BASELO] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OITAXFROM] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIHANTYP] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIPRICIE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OITAXTO] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OITAXCON] [numeric](17, 2) NULL,
	[OITAXGRP] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIOILCON] [numeric](6, 2) NULL,
	[OIINEX] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIEXGNUM] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIEXGTYP] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIFEETOT] [numeric](18, 2) NULL,
	[OIFEEDT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OINETCYC] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIFERP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIFEECH] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIA_IPMVAT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIA_SPLTIV] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIVATH] [numeric](16, 2) NULL,
	[OIVATF] [numeric](16, 2) NULL,
	[OISBREL] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIBASPROD] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OITRKNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OITRKJR] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIEXTNR] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIITMNR] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIFTIND] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIPRIOP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OITRIND] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIGHNDL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIUMBAR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OITXCON1] [numeric](17, 2) NULL,
	[OITXCON2] [numeric](17, 2) NULL,
	[OITXCON3] [numeric](17, 2) NULL,
	[OITXCON4] [numeric](17, 2) NULL,
	[OITXCON5] [numeric](17, 2) NULL,
	[OITXCON6] [numeric](17, 2) NULL,
	[OID_EXTBOL] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OID_MISCDL] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIMATCYC] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIEDOK] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIEDBAL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIEDBALM] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OICERTF1] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIDATFM1] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIDATTO1] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIH_LICTP] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIH_LICIN] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIH_LCFOL] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIH_FOLQTY] [numeric](17, 3) NULL,
	[OIEDOK_GI] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIEDBAL_GI] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIEDBALM_GI] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIHANTYP_GI] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIINEX_GI] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OITAXGRP_GI] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OICERTF1_GI] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIDATFM1_GI] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIDATTO1_GI] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIH_LICTP_GI] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIH_LICIN_GI] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIH_LCFOL_GI] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIH_FOLQTY_GI] [numeric](17, 3) NULL,
	[OIO_RFBLN] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIO_RFBLP] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SGT_SCAT] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SGT_RCAT] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TMS_REF_UUID] [nvarchar](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WRF_CHARSTC1] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WRF_CHARSTC2] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WRF_CHARSTC3] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZDUMMY] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZDATA1] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZDATA2] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZDATA3] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZDATA4] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REFSITE] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZAPCGK] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[APCGK_EXTEND] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZBAS_DATE] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZADATTYP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZSTART_DAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Z_DEV] [numeric](7, 3) NULL,
	[ZINDANX] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZLIMIT_DAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NUMERATOR] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HASHCAL_BDAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HASHCAL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NEGATIVE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HASHCAL_EXISTS] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KNOWN_INDEX] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/SAPMP/GPOSE] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ANGPN] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADMOI] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADPRI] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LPRIO] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADACN] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AFPNR] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BSARK] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUDAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ANGNR] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PNSTAT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDNS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SERRU] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SERNP] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISUB_SOBKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISUB_PSPNR] [nvarchar](24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISUB_KUNNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISUB_VBELN] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISUB_POSNR] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISUB_OWNER] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_SEASON_YEAR] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_SEASON] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_COLLECTION] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_THEME] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_ATP_DATE] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_VAS_REL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_VAS_PRNT_ID] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_TRANSACTION] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_ITEM_GROUP] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_ITEM] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_SS] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_GRID_COND_REC] [nvarchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_PSM_PFM_SPLIT] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CNFM_QTY] [numeric](18, 3) NULL,
	[FSH_PQR_UEPOS] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RFM_DIVERSION] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STPAC] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LGBZO] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LGBZO_B] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDRNUM] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONSNUM] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BORGR_MISS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEP_ID] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BELNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KBLPOS_CAB] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KBLNR_COMP] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KBLPOS_COMP] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WBS_ELEMENT] [nvarchar](24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RFM_PSST_RULE] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RFM_PSST_GROUP] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RFM_REF_DOC] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RFM_REF_ITEM] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RFM_REF_ACTION] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RFM_REF_SLITEM] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REF_ITEM] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SOURCE_ID] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SOURCE_KEY] [nvarchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PUT_BACK] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_ID] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONS_ORDER] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
