SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [lnd].[EBAN_purchase_requisition](
	[MANDT] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BANFN] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BNFPO] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BSART] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BSTYP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BSAKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOEKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STATU] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ESTKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FRGKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FRGZU] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FRGST] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EKGRP] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ERNAM] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ERDAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AFNAM] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TXZ01] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MATNR] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMATN] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WERKS] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LGORT] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BEDNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MATKL] [nvarchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RESWK] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MENGE] [numeric](17, 3) NULL,
	[MEINS] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BUMNG] [numeric](17, 3) NULL,
	[BADAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LPEIN] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LFDAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FRGDT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WEBAZ] [numeric](3, 0) NULL,
	[PREIS] [numeric](14, 2) NULL,
	[PEINH] [numeric](6, 0) NULL,
	[PSTYP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KNTTP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZVBR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KFLAG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VRTKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TWRKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WEPOS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WEUNB] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REPOS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LIFNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FLIEF] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EKORG] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VRTYP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KONNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KTPNR] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INFNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZUGBA] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QUNUM] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QUPOS] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISPO] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SERNR] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BVDAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BATOL] [numeric](3, 0) NULL,
	[BVDRK] [numeric](7, 0) NULL,
	[EBELN] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EBELP] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BEDAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BSMNG] [numeric](17, 3) NULL,
	[LBLNI] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BWTAR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[XOBLR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EBAKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RSNUM] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SOBKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ARSNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ARSPS] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIXKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BMEIN] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REVLV] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VORAB] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PACKNO] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KANBA] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BPUEB] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CUOBJ] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FRGGR] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FRGRL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AKTNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CHARG] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UMSOK] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VERID] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIPOS] [nvarchar](24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FISTL] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GEBER] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZKFG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SATNR] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MNG02] [numeric](18, 3) NULL,
	[DAT01] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ATTYP] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADRNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADRN2] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KUNNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMLIF] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LBLKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZBWS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WAERS] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDNLF] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GSFRG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MPROF] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZFME] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPRAS] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TECHS] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MFRPN] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MFRNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMNFR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FORDN] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FORDP] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PLIFZ] [numeric](3, 0) NULL,
	[BERID] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UZEIT] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FKBER] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GRANT_NBR] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MEMORY] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BANPR] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RLWRT] [numeric](20, 2) NULL,
	[BLCKD] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REVNO] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BLCKT] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BESWK] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EPROFILE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EPREFDOC] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EPREFITM] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GMMNG] [numeric](17, 3) NULL,
	[WRTKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RESLO] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KBLNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KBLPOS] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRIO_URG] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRIO_REQ] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MEMORYTYPE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ANZSN] [int] NULL,
	[MHDRZ] [numeric](5, 0) NULL,
	[IPRKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NODISP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SRM_CONTRACT_ID] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SRM_CONTRACT_ITM] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BUDGET_PD] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ELDAT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DUMMY_EBAN_INCL_EEW_PS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_CATALOG_ID] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STORENETWORKID] [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STORESUPPLIERID] [nvarchar](64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CREATIONDATE] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CREATIONTIME] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRODUCTTYPE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SERVICEPERFORMER] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ISEOPBLOCKED] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXT_REV_TMSTMP] [numeric](27, 7) NULL,
	[FMFGUS_KEY] [nvarchar](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STARTDATE] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENDDATE] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXTMATERIALFORPURG] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXTFIXEDSUPPLIERFORPURG] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXTDESIREDSUPPLIERFORPURG] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXTCONTRACTFORPURG] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXTCONTRACTITEMFORPURG] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXTINFORECORDFORPURG] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXTPLANTFORPURG] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXTCOMPANYCODEFORPURG] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXTPURGORGFORPURG] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXTSOURCESYSTEM] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXT_BE_SOURCE_SYS] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXTAPPROVALSTATUS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PURCHASEREQNITEMUNIQUEID] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LASTCHANGEDATETIME] [numeric](27, 7) NULL,
	[ISONBEHALFCART] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXPECTED_VALUE] [numeric](16, 2) NULL,
	[LIMIT_AMOUNT] [numeric](16, 2) NULL,
	[ADVCODE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STACODE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BANFN_CS] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BNFPO_CS] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ITEM_CS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BSMNG_SND] [numeric](17, 3) NULL,
	[NO_MARD_DATA] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADMOI] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADPRI] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LPRIO] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADACN] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADDNS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SERRU] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISUB_SOBKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISUB_PSPNR] [nvarchar](24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISUB_KUNNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISUB_VBELN] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISUB_POSNR] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISUB_OWNER] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_VAS_REL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_VAS_PRNT_ID] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_TRANSACTION] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_ITEM_GROUP] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_ITEM] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IUID_RELEVANT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SC_SR_ITEM_KEY] [int] NULL,
	[SC_CATALOGID] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SC_CATALOGITEM] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SC_REQUESTOR] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SC_AUTHOR] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OITAXFROM] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIHANTYP] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OITAXTO] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OITAXGRP] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIOILCON] [numeric](6, 2) NULL,
	[OIINEX] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIPRICIE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIO_SPROC] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIO_STATUS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIO_REF_BANFN] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIO_REF_BNFPO] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIO_HOLD] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SGT_SCAT] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SGT_RCAT] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WRF_CHARSTC1] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WRF_CHARSTC2] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WRF_CHARSTC3] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
