SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [lnd].[MARA_material_data](
	[MANDT] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MATNR] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ERSDA] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ERNAM] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LAEDA] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AENAM] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VPSTA] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PSTAT] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LVORM] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MTART] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MBRSH] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MATKL] [nvarchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BISMT] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MEINS] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BSTME] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZEINR] [nvarchar](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZEIAR] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZEIVR] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZEIFO] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AESZN] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BLATT] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BLANZ] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FERTH] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FORMT] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GROES] [nvarchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WRKST] [nvarchar](48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NORMT] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LABOR] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EKWSL] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BRGEW] [numeric](17, 3) NULL,
	[NTGEW] [numeric](17, 3) NULL,
	[GEWEI] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VOLUM] [numeric](17, 3) NULL,
	[VOLEH] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BEHVO] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RAUBE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TEMPB] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DISST] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TRAGR] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STOFF] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPART] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KUNNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EANNR] [nvarchar](13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WESCH] [numeric](17, 3) NULL,
	[BWVOR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BWSCL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SAISO] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ETIAR] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ETIFO] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENTAR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EAN11] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NUMTP] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LAENG] [numeric](17, 3) NULL,
	[BREIT] [numeric](17, 3) NULL,
	[HOEHE] [numeric](17, 3) NULL,
	[MEABM] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRDHA] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AEKLK] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CADKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QMPUR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ERGEW] [numeric](17, 3) NULL,
	[ERGEI] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ERVOL] [numeric](17, 3) NULL,
	[ERVOE] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GEWTO] [numeric](4, 1) NULL,
	[VOLTO] [numeric](4, 1) NULL,
	[VABME] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZREV] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZKFG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[XCHPF] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VHART] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FUELG] [numeric](3, 0) NULL,
	[STFAK] [smallint] NULL,
	[MAGRV] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BEGRU] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATAB] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LIQDT] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SAISJ] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PLGTP] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MLGUT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXTWG] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SATNR] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ATTYP] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZKUP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZNFM] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PMATA] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MSTAE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MSTAV] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MSTDE] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MSTDV] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TAKLV] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RBNRM] [nvarchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MHDRZ] [numeric](5, 0) NULL,
	[MHDHB] [numeric](5, 0) NULL,
	[MHDLP] [numeric](3, 0) NULL,
	[INHME] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INHAL] [numeric](17, 3) NULL,
	[VPREH] [numeric](6, 0) NULL,
	[ETIAG] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INHBR] [numeric](17, 3) NULL,
	[CMETH] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CUOBF] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZUMW] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KOSCH] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPROF] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NRFHG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MFRPN] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MFRNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BMATN] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MPROF] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZWSM] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SAITY] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PROFL] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IHIVI] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ILOOS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SERLV] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZGVH] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[XGCHP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZEFF] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMPL] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IPRKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RDMHD] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRZUS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MTPOS_MARA] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BFLME] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MATFI] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CMREL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BBTYP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SLED_BBD] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GTIN_VARIANT] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GENNR] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RMATP] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GDS_RELEVANT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WEORA] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HUTYP_DFLT] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PILFERABLE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WHSTC] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WHMATGR] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HNDLCODE] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HAZMAT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HUTYP] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TARE_VAR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAXC] [numeric](20, 3) NULL,
	[MAXC_TOL] [numeric](4, 1) NULL,
	[MAXL] [numeric](19, 3) NULL,
	[MAXB] [numeric](19, 3) NULL,
	[MAXH] [numeric](19, 3) NULL,
	[MAXDIM_UOM] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HERKL] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MFRGR] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QQTIME] [numeric](3, 0) NULL,
	[QQTIMEUOM] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QGRP] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SERIAL] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PS_SMARTFORM] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOGUNIT] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CWQREL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CWQPROC] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CWQTOLGR] [nvarchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADPROF] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IPMIPPRODUCT] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ALLOW_PMAT_IGNO] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MEDIUM] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMMODITY] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ANIMAL_ORIGIN] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TEXTILE_COMP_IND] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LAST_CHANGED_TIME] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MATNR_EXTERNAL] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOGISTICAL_MAT_CATEGORY] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SALES_MATERIAL] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDENTIFICATION_TAG_TYPE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SGT_CSGR] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SGT_COVSA] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SGT_STAT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SGT_SCOPE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SGT_REL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ANP] [nvarchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PSM_CODE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_MG_AT1] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_MG_AT2] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_MG_AT3] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_SEALV] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_SEAIM] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_SC_MID] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DUMMY_PRD_INCL_EEW_PS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_MATID_GUID16] [nvarchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_MATID_GUID22] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCM_MATURITY_DUR] [numeric](11, 0) NULL,
	[SCM_SHLF_LFE_REQ_MIN] [numeric](11, 0) NULL,
	[SCM_SHLF_LFE_REQ_MAX] [numeric](11, 0) NULL,
	[SCM_PUOM] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RMATP_PB] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PROD_SHAPE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MO_PROFILE_ID] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OVERHANG_TRESH] [numeric](6, 2) NULL,
	[BRIDGE_TRESH] [numeric](6, 2) NULL,
	[BRIDGE_MAX_SLOPE] [numeric](6, 2) NULL,
	[HEIGHT_NONFLAT] [numeric](17, 3) NULL,
	[HEIGHT_NONFLAT_UOM] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/CWM/XCWMAT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/CWM/VALUM] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/CWM/TOLGR] [nvarchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/CWM/TARA] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/CWM/TARUM] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/BEV1/LULEINH] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/BEV1/LULDEGRP] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/BEV1/NESTRUCCAT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/DSD/SL_TOLTYP] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/DSD/SV_CNT_GRP] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/DSD/VC_GROUP] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/SAPMP/KADU] [numeric](9, 2) NULL,
	[/SAPMP/ABMEIN] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/SAPMP/KADP] [numeric](6, 2) NULL,
	[/SAPMP/BRAD] [numeric](5, 0) NULL,
	[/SAPMP/SPBI] [numeric](9, 2) NULL,
	[/SAPMP/TRAD] [numeric](9, 2) NULL,
	[/SAPMP/KEDU] [numeric](9, 2) NULL,
	[/SAPMP/SPTR] [numeric](17, 3) NULL,
	[/SAPMP/FBDK] [numeric](9, 2) NULL,
	[/SAPMP/FBHK] [numeric](9, 2) NULL,
	[/SAPMP/RILI] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/SAPMP/FBAK] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/SAPMP/AHO] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/SAPMP/MIFRR] [numeric](9, 2) NULL,
	[/STTPEC/SERTYPE] [tinyint] NULL,
	[/STTPEC/SYNCACT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/STTPEC/SYNCTIME] [numeric](19, 0) NULL,
	[/STTPEC/SYNCCHG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/STTPEC/COUNTRY_REF] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/STTPEC/PRDCAT] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/VSO/R_TILT_IND] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/VSO/R_STACK_IND] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/VSO/R_BOT_IND] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/VSO/R_TOP_IND] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/VSO/R_STACK_NO] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/VSO/R_PAL_IND] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/VSO/R_PAL_OVR_D] [numeric](17, 3) NULL,
	[/VSO/R_PAL_OVR_W] [numeric](17, 3) NULL,
	[/VSO/R_PAL_B_HT] [numeric](17, 3) NULL,
	[/VSO/R_PAL_MIN_H] [numeric](17, 3) NULL,
	[/VSO/R_TOL_B_HT] [numeric](17, 3) NULL,
	[/VSO/R_NO_P_GVH] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/VSO/R_QUAN_UNIT] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[/VSO/R_KZGVH_IND] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PACKCODE] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DG_PACK_STATUS] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MCOND] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RETDELC] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOGLEV_RETO] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NSNID] [nvarchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OVLPN] [nvarchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADSPC_SPC] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VARID] [nvarchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MSBOOKPARTNO] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DPCBT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[XGRDT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IMATN] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PICNUM] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BSTAT] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COLOR_ATINN] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SIZE1_ATINN] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SIZE2_ATINN] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COLOR] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SIZE1] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SIZE2] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FREE_CHAR] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CARE_CODE] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BRAND_ID] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIBER_CODE1] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIBER_PART1] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIBER_CODE2] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIBER_PART2] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIBER_CODE3] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIBER_PART3] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIBER_CODE4] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIBER_PART4] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIBER_CODE5] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIBER_PART5] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FASHGRD] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIGROUPNAM] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OITRIND] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIHMTXGR] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_COMMODITY] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_COPA_MEINS1] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_ATT01] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_ATT02] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_ATT03] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZZ_RRP_PRIO] [int] NULL
) ON [PRIMARY]

GO
