SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [lnd].[T001W_plant_data](
	[MANDT] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WERKS] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAME1] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BWKEY] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KUNNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LIFNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FABKL] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAME2] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STRAS] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PFACH] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PSTLZ] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORT01] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EKORG] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VKORG] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CHAZV] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KKOWK] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KORDB] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BEDPL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LAND1] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REGIO] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COUNC] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CITYC] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ADRNR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IWERK] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TXJCD] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VTWEG] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPART] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPRAS] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WKSOP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AWSLS] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CHAZV_OLD] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VLFKZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BZIRK] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZONE1] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TAXIW] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BZQHL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LET01] [numeric](4, 0) NULL,
	[LET02] [numeric](4, 0) NULL,
	[LET03] [numeric](4, 0) NULL,
	[TXNAM_MA1] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TXNAM_MA2] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TXNAM_MA3] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BETOL] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[J_1BBRANCH] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VTBFI] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FPRFW] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACHVM] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DVSART] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NODETYPE] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NSCHEMA] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PKOSA] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MISCH] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MGVUPD] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VSTEL] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MGVLAUPD] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MGVLAREVAL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SOURCING] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NO_DEFAULT_BATCH_MANAGEMENT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_MG_ARUN_REQ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_SEAIM] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_BOM_MAINTENANCE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FSH_GROUP_PR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ARUN_FIX_BATCH] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OILIVAL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIHVTYPE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OIHCREDIPI] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STORETYPE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEP_STORE] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
