SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [lnd].[T134_Material_Type](
	[MANDT] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MTART] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MTREF] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MBREF] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FLREF] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NUMKI] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NUMKE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENVOP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BSEXT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BSINT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PSTAT] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KKREF] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VPRSV] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZVPR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VMTPO] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EKALR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZGRP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZKFG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BEGRU] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZPRC] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZPIP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRDRU] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ARANZ] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WMAKG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IZUST] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ARDEL] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZMPN] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MSTAE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCHIS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CTYPE] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLASS] [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CHNEU] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PROD_TYPE_CODE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONCTD_MATNR] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VTYPE] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VNUMKI] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VNUMKE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZFFF] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KZRAC] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
