SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [lnd].[CEPC_Profit_Center_Master](
	[MANDT] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRCTR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATBI] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KOKRS] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATAB] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ERSDA] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[USNAM] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MERKMAL] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ABTEI] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VERAK] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VERAK_USER] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WAERS] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NPRCTR] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LAND1] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ANRED] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAME1] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAME2] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAME3] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAME4] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORT01] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORT02] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STRAS] [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PFACH] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PSTLZ] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PSTL2] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPRAS] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TELBX] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TELF1] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TELF2] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TELFX] [nvarchar](31) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TELTX] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TELX1] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATLT] [nvarchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRNAM] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KHINR] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BUKRS] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VNAME] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RECID] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ETYPE] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TXJCD] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REGIO] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KVEWE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KAPPL] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KALSM] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOGSYSTEM] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOCK_IND] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PCA_TEMPLATE] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SEGMENT] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EEW_CEPC_PS_DUMMY] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
