ALTER DATABASE [$(DatabaseName)]
    ADD FILE (NAME = [DSQLT], FILENAME = 'D:\Daten\SQL2008\MSSQL10_50.R2\MSSQL\DATA\DSQLT.MDF', SIZE = 2304 KB, MAXSIZE = UNLIMITED, FILEGROWTH = 1024 KB) TO FILEGROUP [PRIMARY];



