SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [CTE].[ReplaceData](
	[old] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[new] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
