SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [CTE].[HUB_Stock](
	[StockId] [int] IDENTITY(1,1) NOT NULL,
	[StockCode] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
