SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [IMAGES].[Images2](
	[ID] [int] NOT NULL,
	[ImageBase64] [varchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
