SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ETL].[JobGroupToJob](
	[JobGroupToJobID] [int] IDENTITY(1,1) NOT NULL,
	[JobGroupID] [int] NOT NULL,
	[JobID] [int] NOT NULL,
	[LoadDT]  AS (CONVERT([datetime2](7),getdate())),
 CONSTRAINT [PK_JobGroupToJob] PRIMARY KEY CLUSTERED 
(
	[JobGroupToJobID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
