SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ETL].[JobRunOrder](
	[JobRunOrderID] [int] IDENTITY(1,1) NOT NULL,
	[JobBatchID] [int] NULL,
	[JobGroupID] [int] NULL,
	[JobID] [int] NOT NULL,
	[JobRunOrder] [int] NOT NULL,
	[CreatedDT]  AS (CONVERT([datetime2](7),getdate())),
	[UpdatedDT] [datetime2](7) NULL,
	[IsActive] [bit] NULL,
 CONSTRAINT [PK_JobRunOrder] PRIMARY KEY CLUSTERED 
(
	[JobRunOrderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [ETL].[JobRunOrder] ADD  DEFAULT ((1)) FOR [IsActive]
GO
