SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dm].[DD02V_Generated_Table_for_View_PROD]') AND type in (N'U'))
BEGIN
CREATE TABLE [dm].[DD02V_Generated_Table_for_View_PROD](
	[TABNAME] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[DDLANGUAGE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TABCLASS] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SQLTAB] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATMIN] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATMAX] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATAVG] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLIDEP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BUFFERED] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMPRFLAG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LANGDEP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DDTEXT] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACTFLAG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[APPLCLASS] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUTHCLASS] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AS4USER] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AS4DATE] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AS4TIME] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MASTERLANG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAINFLAG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONTFLAG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RESERVETAB] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GLOBALFLAG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PROZPUFF] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VIEWCLASS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VIEWGRANT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MULTIPLEX] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHLPEXI] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PROXYTYPE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXCLASS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WRONGCL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ALWAYSTRP] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ALLDATAINCL] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WITH_PARAMETERS] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXVIEW_INCLUDED] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KEYMAX_FEATURE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KEYLEN_FEATURE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TABLEN_FEATURE] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NONTRP_INCLUDED] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VIEWREF] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VIEWREF_ERR] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VIEWREF_POS_CHG] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TBFUNC_INCLUDED] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IS_GTT] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SESSION_VAR_EX] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FROM_ENTITY] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PK_IS_INVHASH] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[USED_SESSION_VARS] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HDB_ONLY_ENTITY_INCLUDED] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_DD02V] PRIMARY KEY CLUSTERED 
(
	[TABNAME] ASC,
	[DDLANGUAGE] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dm].[DD02V_Generated_Table_for_View_PROD]') AND name = N'ncix01_DD02V')
CREATE NONCLUSTERED INDEX [ncix01_DD02V] ON [dm].[DD02V_Generated_Table_for_View_PROD]
(
	[DDLANGUAGE] ASC
)
INCLUDE([TABCLASS],[SQLTAB],[CLIDEP],[LANGDEP],[DDTEXT],[APPLCLASS],[VIEWCLASS],[PROXYTYPE],[EXCLASS],[ALWAYSTRP],[ALLDATAINCL],[NONTRP_INCLUDED]) WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dm].[DD02V_Generated_Table_for_View_PROD]') AND name = N'ncix02_DD02V')
CREATE NONCLUSTERED INDEX [ncix02_DD02V] ON [dm].[DD02V_Generated_Table_for_View_PROD]
(
	[TABNAME] ASC
)
INCLUDE([DDTEXT]) WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
GO
