SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [raw].[SAT_CreditNote_ATS_LVD](
	[HK_CreditNote] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[LoadDT] [datetime2](7) NULL,
	[LoadEndDT] [datetime2](7) NULL,
	[RecSrcDataEntityID] [int] NULL,
	[HashDiff] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OBL_AUDTDATE] [decimal](9, 0) NULL,
	[OBL_AUDTTIME] [decimal](9, 0) NULL,
	[OBL_AUDTUSER] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUDTORG] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDORDERNBR] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDCUSTPO] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATEDUE] [decimal](9, 0) NULL,
	[IDNATACCT] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TRXTYPEID] [smallint] NULL,
	[TRXTYPETXT] [smallint] NULL,
	[DATEBTCH] [decimal](9, 0) NULL,
	[CNTBTCH] [decimal](9, 0) NULL,
	[CNTITEM] [decimal](7, 0) NULL,
	[IDGRP] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DESCINVC] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATEINVC] [decimal](9, 0) NULL,
	[DATEASOF] [decimal](9, 0) NULL,
	[CODETERM] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODECURN] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDRATETYPE] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXCHRATEHC] [decimal](15, 7) NULL,
	[AMTINVCHC] [decimal](19, 3) NULL,
	[AMTDUEHC] [decimal](19, 3) NULL,
	[AMTTXBLHC] [decimal](19, 3) NULL,
	[AMTTAXHC] [decimal](19, 3) NULL,
	[AMTINVCTC] [decimal](19, 3) NULL,
	[AMTDUETC] [decimal](19, 3) NULL,
	[AMTTXBLTC] [decimal](19, 3) NULL,
	[AMTTAXTC] [decimal](19, 3) NULL,
	[AMTDISCTC] [decimal](19, 3) NULL,
	[CODETAX1] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AMTBASE1HC] [decimal](19, 3) NULL,
	[AMTTAX1HC] [decimal](19, 3) NULL,
	[AMTBASE1TC] [decimal](19, 3) NULL,
	[AMTTAX1TC] [decimal](19, 3) NULL,
	[FISCYR] [char](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FISCPER] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATEBUS] [decimal](9, 0) NULL,
	[RATEDATE] [decimal](9, 0) NULL,
	[RATEOP] [smallint] NULL,
	[POSTSEQNCE] [decimal](9, 0) NULL,
	[INVCTYPE] [smallint] NULL,
	[TYPEBTCH] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CNTOBLJ] [int] NULL,
	[CODECURNRC] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RATERC] [decimal](15, 7) NULL,
	[CODETAXGRP] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TAXVERSION] [int] NULL,
	[TAXCLASS1] [smallint] NULL,
	[ORATE] [decimal](15, 7) NULL,
	[ORATETYPE] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORATEDATE] [decimal](9, 0) NULL,
	[ORATEOP] [smallint] NULL
) ON [PRIMARY]

GO
