SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[Tests2](
	[testid] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TestName] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]

GO
