SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON


CREATE   PROCEDURE ETL.TryCatchBlcok
AS 
BEGIN
	SET XACT_ABORT, NOCOUNT ON
	   BEGIN TRY
		  BEGIN TRANSACTION

			DECLARE @a VARCHAR(10) = 'vala'
			DECLARE @b VARCHAR(10) = 'valb'

		  	DROP TABLE IF EXISTS ETL.SampleTable
	
			CREATE TABLE ETL.SampleTable (
				a VARCHAR(10) PRIMARY KEY ,
				b VARCHAR(10)
			)

			INSERT ETL.SampleTable(a,b) VALUES (@a, @b)
			INSERT ETL.SampleTable(a,b) VALUES (@a, @b)

		  COMMIT TRANSACTION
	   END TRY
	   BEGIN CATCH
		  IF @@trancount > 0 ROLLBACK TRANSACTION
		  DECLARE @msg nvarchar(2048) = error_message()  
		  RAISERROR (@msg, 16, 1)
		  RETURN 55555
	   END CATCH


END
GO
