SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
/*
	EXEC dbo.test_Window_First_Last
*/
CREATE   PROCEDURE dbo.test_Window_First_Last
AS

DROP TABLE IF EXISTS [dbo].[Window_First_Last]

CREATE TABLE [dbo].[Window_First_Last](
 [id] [int] IDENTITY(1,1) NOT NULL,
 [Department] [nchar](10) NOT NULL,
 [DateUpdate] DATE NOT NULL,
 [Code] [int] NOT NULL,
 CONSTRAINT [PK_Window_First_Last] PRIMARY KEY CLUSTERED 
(
 [id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
