SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE VIEW [dbo].[vw_AROBP] AS
      SELECT  [IDCUST]
      ,[IDINVC]
      ,[CNTPAYMNBR]
      ,[IDRMIT]
      ,[DATEBUS]
      ,[TRANSTYPE]
      ,[CNTSEQNCE]
      ,DEV_InfoMart.dbo.udf_convertDate_Sage300_UTC([AUDTDATE]) AS AUDTDATE
      ,[AUDTTIME]
      ,[AUDTUSER]
      ,[AUDTORG]
      ,[DEPSTNBR]
      ,[CNTBTCH]
      ,[DATEBTCH]
      ,[AMTPAYMHC]
      ,[AMTPAYMTC]
      ,[CODECURN]
      ,[IDRATETYPE]
      ,[RATEEXCHHC]
      ,[SWOVRDRATE]
      ,[IDBANK]
      ,[TRXTYPE]
      ,[IDMEMOXREF]
      ,[SWINVCDEL]
      ,[DATELSTSTM]
      ,[IDPREPAID]
      ,[IDCUSTRMIT]
      ,[DATERMIT]
      ,[CNTITEM]
      ,[FISCYR]
      ,[FISCPER]
      ,[RATEDATE]
      ,[RATEOP]
      ,[STMTSEQ]
      ,[PYMCUID]
      ,[DEPSEQ]
      ,[DEPLINE]
  FROM [ODS_ATSDAT].[dbo].[AROBP]
  WHERE IDCUST = 'KEV100'

GO
