SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE VIEW [DV].[vw_DMOD_UnappliedCashAppliedToInvoice]
AS
	SELECT 
		[obp].[IDINVC]
	,	[obp].[IDMEMOXREF]
	FROM 
		 [ODS_ATSDAT].[dbo].[AROBP] AS [obp]
	WHERE
		[obp].[TRXTYPE] = 3
	AND 
		[obp].[TRANSTYPE] = 5
	AND 
	[obp].[IDCUST] = 'KEV100'
	AND [obp].[IDMEMOXREF] IN ( 'INV201909615' , 'INV202001261',
	'INV202001020')
	AND 
		SUBSTRING([obp].[IDMEMOXREF], 1, 2) IN ('IN')

GO
