SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON


CREATE   VIEW [DV].[vw_DMOD_ARCustomer]
AS 

SELECT
	   cus.[IDCUST]
      , IIF(DEV_InfoMart.dbo.udf_convertDateTime_Sage300_UTC(cus.[AUDTDATE], cus.[AUDTTIME]) >= DEV_InfoMart.dbo.udf_convertDateTime_Sage300_UTC(custdate.[AUDTDATE]
							, custdate.[AUDTTIME]), cus.[AUDTDATE], custdate.[AUDTDATE]) AS [AUDTDATE]
	  , IIF(DEV_InfoMart.dbo.udf_convertDateTime_Sage300_UTC(cus.[AUDTDATE], cus.[AUDTTIME]) >= DEV_InfoMart.dbo.udf_convertDateTime_Sage300_UTC(custdate.[AUDTDATE]
							, custdate.[AUDTTIME]), cus.[AUDTTIME], custdate.[AUDTTIME]) AS [AUDTTIME]
      ,cus.[AUDTUSER]
      ,cus.[AUDTORG]
      ,cus.[TEXTSNAM]
      ,cus.[IDGRP]
      ,cus.[IDNATACCT]
      ,cus.[SWACTV]
      ,cus.[DATEINAC]
      ,cus.[DATELASTMN]
      ,cus.[SWHOLD]
      ,cus.[DATESTART]
      ,cus.[NAMECUST]
      ,cus.[TEXTSTRE1]
      ,cus.[TEXTSTRE2]
      ,cus.[TEXTSTRE3]
      ,cus.[TEXTSTRE4]
      ,cus.[NAMECITY]
      ,cus.[CODESTTE]
      ,cus.[CODEPSTL]
      ,cus.[CODECTRY]
      ,cus.[NAMECTAC]
      ,cus.[TEXTPHON1]
      ,cus.[TEXTPHON2]
      ,cus.[CODETERR]
      ,cus.[IDACCTSET]
      ,cus.[IDBILLCYCL]
      ,cus.[IDSVCCHRG]
      ,cus.[CODECURN]
      ,cus.[SWPRTSTMT]
      ,cus.[SWPRTDLNQ]
      ,cus.[SWBALFWD]
      ,cus.[CODETERM]
      ,cus.[IDRATETYPE]
      ,cus.[CODETAXGRP]
      ,cus.[IDTAXREGI1]
      ,cus.[TAXSTTS1]
      ,cus.[AMTCRLIMT]
      ,cus.[AMTBALDUET]
      ,cus.[AMTBALDUEH]
      ,cus.[DATELASTST]
      ,cus.[AMTLASTSTT]
      ,cus.[AMTLASTSTH]
      ,cus.[DTBEGBALFW]
      ,cus.[AMTBALFWDT]
      ,cus.[AMTBALFWDH]
      ,cus.[DTLASTRVAL]
      ,cus.[AMTBALLARV]
      ,cus.[CNTOPENINV]
      ,cus.[CNTINVPAID]
      ,cus.[DAYSTOPAY]
      ,cus.[DATEINVCHI]
      ,cus.[DATEBALHI]
      ,cus.[DATELASTAC]
      ,cus.[DATELASTIV]
      ,cus.[DATELASTCR]
      ,cus.[DATELASTDR]
      ,cus.[DATELASTPA]
      ,cus.[DATELASTDI]
      ,cus.[DATELASTAD]
      ,cus.[DATELASTWR]
      ,cus.[DATELASTRI]
      ,cus.[DATELASTIN]
      ,cus.[DATELASTDQ]
      ,cus.[IDINVCHI]
      ,cus.[IDINVCHILY]
      ,cus.[AMTINVHIT]
      ,cus.[AMTBALHIT]
      ,cus.[AMTINVHILT]
      ,cus.[AMTBALHILT]
      ,cus.[AMTLASTIVT]
      ,cus.[AMTLASTCRT]
      ,cus.[AMTLASTDRT]
      ,cus.[AMTLASTPYT]
      ,cus.[AMTLASTDIT]
      ,cus.[AMTLASTADT]
      ,cus.[AMTLASTWRT]
      ,cus.[AMTLASTRIT]
      ,cus.[AMTLASTINT]
      ,cus.[AMTINVHIH]
      ,cus.[AMTBALHIH]
      ,cus.[AMTINVHILH]
      ,cus.[AMTBALHILH]
      ,cus.[AMTLASTIVH]
      ,cus.[AMTLASTCRH]
      ,cus.[AMTLASTDRH]
      ,cus.[AMTLASTPYH]
      ,cus.[AMTLASTDIH]
      ,cus.[AMTLASTADH]
      ,cus.[AMTLASTWRH]
      ,cus.[AMTLASTRIH]
      ,cus.[AMTLASTINH]
      ,cus.[PRICLIST]
      ,cus.[CUSTTYPE]
      ,cus.[AMTPDUE]
      ,cus.[EMAIL1]
      ,cus.[EMAIL2]
      ,cus.[WEBSITE]
      ,cus.[BILLMETHOD]
      ,cus.[PAYMCODE]
      ,cus.[FOB]
      ,cus.[SHPVIACODE]
      ,cus.[SHPVIADESC]
      ,cus.[DELMETHOD]
      ,cus.[PRIMSHIPTO]
      ,cus.[CTACPHONE]
      ,cus.[CTACFAX]
      ,cus.[SWPARTSHIP]
      ,cus.[SWWEBSHOP]
      ,cus.[RTGPERCENT]
      ,cus.[RTGDAYS]
      ,cus.[RTGTERMS]
      ,cus.[RTGAMTTC]
      ,cus.[RTGAMTHC]
      ,cus.[VALUES]
      ,cus.[CNTPPDINVC]
      ,cus.[AMTPPDINVT]
      ,cus.[AMTPPDINVH]
      ,cus.[DATELASTRF]
      ,cus.[AMTLASTRFT]
      ,cus.[AMTLASTRFH]
      ,cus.[CODECHECK]
      ,cus.[NEXTCUID]
      ,cus.[LOCATION]
      ,cus.[SWCHKLIMIT]
      ,cus.[SWCHKOVER]
      ,cus.[OVERDAYS]
      ,cus.[OVERAMT]
      ,cus.[SWBACKORDR]
      ,cus.[SWCHKDUPPO]
      ,cus.[CATEGORY]
      ,cus.[BRN]
	  ,PivotTable.CRM
	  ,PivotTable.MAN
	  ,PivotTable.DIR
  FROM [ODS_ATSDAT].[dbo].[ARCUS] cus
  LEFT JOIN
  (
			 SELECT 
					cuso.[IDCUST]
				,	cuso.[VALUE] 
				,	cuso.[OPTFIELD]
			 FROM 
				[dbo].[ARCUSO] as cuso
) AS SourceTable PIVOT(MAX([VALUE]) FOR [OPTFIELD] IN (
														CRM, 
														MAN, 
														DIR
																
										)
					) AS PivotTable
ON  PivotTable.IDCUST = cus.IDCUST
  LEFT JOIN  (
	SELECT
		cuso2.[IDCUST]
	,	MAX(cuso2.[AUDTDATE]) AS [AUDTDATE]
	,	MAX(cuso2.[AUDTTIME]) AS [AUDTTIME]
	FROM
		[ODS_ATSDAT].[dbo].[ARCUS] cuso2
	GROUP BY
		cuso2.[IDCUST]
	)  custdate
  ON custdate.[IDCUST] = cus.[IDCUST]


GO
