CREATE TABLE [@8].[@6] (
    [@1] NVARCHAR (MAX) NOT NULL,
    [@2] NVARCHAR (MAX) NOT NULL,
    [@3] NVARCHAR (MAX) NOT NULL,
    [@4] NVARCHAR (MAX) NOT NULL,
    [@5] NVARCHAR (MAX) NOT NULL,
    [@6] NVARCHAR (MAX) NULL,
    [@7] NVARCHAR (MAX) NULL,
    [@8] NVARCHAR (MAX) NULL,
    [@9] NVARCHAR (MAX) NULL
);

