SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [ASSESS].[Assessment](
	[AssessmentID] [int] IDENTITY(1,1) NOT NULL,
	[AssessmentName] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CustomerID] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
