SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [ASSESS].[AnswerComment](
	[AnswerCommentID] [int] IDENTITY(1,1) NOT NULL,
	[Comment] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AnswerID] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
