SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [CONFIG].[AXGenericField](
	[AXGenericFieldID] [int] IDENTITY(1,1) NOT NULL,
	[AXGenericFieldName] [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
