SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE VIEW dbo.vw_ReportingHierarchy
AS
SELECT [HashKey] AS [ReportingHierarchyKey]
      ,[CompanyID]
      ,[ReportingHierarchyTypeID]
      ,[ReportingHierarchyTypeCode]
      ,[ReportingHierarchyTypeName]
      ,[ReportingHierarchyItemID]
      ,[ReportingHierarchyItemCode]
      ,[ReportingHierarchyItemName]
      ,[ParentReportingHierarchyItemID]
      ,[ParentReportingHierarchyItemCode]
      ,[ParentReportingHierarchyItemName]
      ,[BusinessKey]
      ,[DataCatalogFieldID]
      ,[FieldName]
      ,[IsDefaultHierarchyItem]
      ,[DomainAccount] AS [UserAccount]
      ,[FirstName]
      ,[Surname]
      ,[Email]
      ,[IsFullAccessUser]
      ,[L1]
      ,[L2]
      ,[L3]
      ,[L4]
      ,[L5]
      ,[L6]
      ,[L7]
      ,[L8]
      ,[L9]
      ,[L10]
      ,[L1SortOrder]
      ,[L2SortOrder]
      ,[L3SortOrder]
      ,[L4SortOrder]
      ,[L5SortOrder]
      ,[L6SortOrder]
      ,[L7SortOrder]
      ,[L8SortOrder]
      ,[L9SortOrder]
      ,[L10SortOrder]
  FROM [DataManager_Local].[ACCESS].[ReportingHierarchyUserAccess]
GO
