SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[reference].[TimeZone]') AND type in (N'U'))
BEGIN
CREATE TABLE [reference].[TimeZone](
	[TimeZoneId] [int] IDENTITY(1,1) NOT NULL,
	[TimeZoneCode] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TimeZoneName] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[TimeZoneId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
