SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

-- REPLACES SPECIAL CHARACTERS FROM STRINGS
CREATE   FUNCTION [dbo].[RemovePatternFromString](@STRINGVALUE VARCHAR(MAX))
RETURNS VARCHAR(MAX) AS
BEGIN
	DECLARE @PATTERN NVARCHAR(128) = '%[$&.!?( ]%'
    DECLARE @POS INT = PATINDEX(@PATTERN, @STRINGVALUE)
    WHILE @POS > 0 BEGIN
        SET @STRINGVALUE = STUFF(@STRINGVALUE, @POS, 1, '_')
        SET @POS = PATINDEX(@PATTERN, @STRINGVALUE)
    END
	SET @STRINGVALUE = REPLACE(REPLACE(REPLACE(REPLACE(@STRINGVALUE , ')',''),'[',''), ']', ''), '__', '')
    RETURN @STRINGVALUE
END
GO
