SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE PROCEDURE [PERFMASTER].[sp_Create_Numbers]
AS

	DECLARE @low INT = 0
	DECLARE @high INT = 10000

	DROP TABLE IF EXISTS [PERFMASTER].[Numbers]

	CREATE TABLE [PERFMASTER].[Numbers] (n INT)

	-- STACKED CTE
	
	
	;WITH e1(n) AS
	(
		SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL 
		SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL 
		SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL 
		SELECT 1 -- 10 
	),
	main AS
	(
		SELECT e1.n
		FROM e1
		CROSS JOIN (SELECT 1 FROM e1) AS e2(n) -- 100 (10^2)
		CROSS JOIN (SELECT 1 FROM e1) AS e3(n) -- 1000 (10^3)
		CROSS JOIN (SELECT 1 FROM e1) AS e4(n) -- 10000 (10^4)
		CROSS JOIN (SELECT 1 FROM e1) AS e5(n) -- 100000 (10^5) 
		CROSS JOIN (SELECT 1 FROM e1) AS e6(n) -- 100000 (10^6) 
	)
	INSERT INTO [PERFMASTER].[Numbers](n)
	SELECT n 
	FROM main 
	WHERE n BETWEEN @low and @high;
GO
