SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [CUST].[DocumentType](
	[TRXTYPETEXTID] [int] NULL,
	[TRXTYPETEXT] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DOCTYPECODE] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DOCTYPENAME] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DOCTYPECODEALT] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DOCTYPENAMEALT] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
