SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[AROBL](
	[IDCUST] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDINVC] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUDTDATE] [decimal](9, 0) NULL,
	[AUDTTIME] [decimal](9, 0) NULL,
	[AUDTUSER] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUDTORG] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDRMIT] [char](24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDORDERNBR] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDCUSTPO] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATEDUE] [decimal](9, 0) NULL,
	[IDNATACCT] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDCUSTSHPT] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TRXTYPEID] [smallint] NULL,
	[TRXTYPETXT] [smallint] NULL,
	[DATEBTCH] [decimal](9, 0) NULL,
	[CNTBTCH] [decimal](9, 0) NULL,
	[CNTITEM] [decimal](7, 0) NULL,
	[IDGRP] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DESCINVC] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATEINVC] [decimal](9, 0) NULL,
	[DATEASOF] [decimal](9, 0) NULL,
	[CODETERM] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATEDISC] [decimal](9, 0) NULL,
	[CODECURN] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDRATETYPE] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SWRATEOVRD] [smallint] NULL,
	[EXCHRATEHC] [decimal](15, 7) NULL,
	[AMTINVCHC] [decimal](19, 3) NULL,
	[AMTDUEHC] [decimal](19, 3) NULL,
	[AMTTXBLHC] [decimal](19, 3) NULL,
	[AMTNONTXHC] [decimal](19, 3) NULL,
	[AMTTAXHC] [decimal](19, 3) NULL,
	[AMTDISCHC] [decimal](19, 3) NULL,
	[AMTINVCTC] [decimal](19, 3) NULL,
	[AMTDUETC] [decimal](19, 3) NULL,
	[AMTTXBLTC] [decimal](19, 3) NULL,
	[AMTNONTXTC] [decimal](19, 3) NULL,
	[AMTTAXTC] [decimal](19, 3) NULL,
	[AMTDISCTC] [decimal](19, 3) NULL,
	[SWPAID] [smallint] NULL,
	[DATELSTACT] [decimal](9, 0) NULL,
	[DATELSTSTM] [decimal](9, 0) NULL,
	[DATELSTDLQ] [decimal](9, 0) NULL,
	[CODEDLQSTS] [smallint] NULL,
	[CNTTOTPAYM] [decimal](5, 0) NULL,
	[CNTLSTPAID] [decimal](5, 0) NULL,
	[CNTLSTPYST] [decimal](5, 0) NULL,
	[AMTREMIT] [decimal](19, 3) NULL,
	[CNTLASTSEQ] [decimal](5, 0) NULL,
	[SWTAXINPUT] [smallint] NULL,
	[CODETAX1] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETAX2] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETAX3] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETAX4] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETAX5] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AMTBASE1HC] [decimal](19, 3) NULL,
	[AMTBASE2HC] [decimal](19, 3) NULL,
	[AMTBASE3HC] [decimal](19, 3) NULL,
	[AMTBASE4HC] [decimal](19, 3) NULL,
	[AMTBASE5HC] [decimal](19, 3) NULL,
	[AMTTAX1HC] [decimal](19, 3) NULL,
	[AMTTAX2HC] [decimal](19, 3) NULL,
	[AMTTAX3HC] [decimal](19, 3) NULL,
	[AMTTAX4HC] [decimal](19, 3) NULL,
	[AMTTAX5HC] [decimal](19, 3) NULL,
	[AMTBASE1TC] [decimal](19, 3) NULL,
	[AMTBASE2TC] [decimal](19, 3) NULL,
	[AMTBASE3TC] [decimal](19, 3) NULL,
	[AMTBASE4TC] [decimal](19, 3) NULL,
	[AMTBASE5TC] [decimal](19, 3) NULL,
	[AMTTAX1TC] [decimal](19, 3) NULL,
	[AMTTAX2TC] [decimal](19, 3) NULL,
	[AMTTAX3TC] [decimal](19, 3) NULL,
	[AMTTAX4TC] [decimal](19, 3) NULL,
	[AMTTAX5TC] [decimal](19, 3) NULL,
	[CODESLSP1] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODESLSP2] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODESLSP3] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODESLSP4] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODESLSP5] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PCTSASPLT1] [decimal](9, 5) NULL,
	[PCTSASPLT2] [decimal](9, 5) NULL,
	[PCTSASPLT3] [decimal](9, 5) NULL,
	[PCTSASPLT4] [decimal](9, 5) NULL,
	[PCTSASPLT5] [decimal](9, 5) NULL,
	[FISCYR] [char](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FISCPER] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDPREPAID] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATEBUS] [decimal](9, 0) NULL,
	[RATEDATE] [decimal](9, 0) NULL,
	[RATEOP] [smallint] NULL,
	[YPLASTACT] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDBANK] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEPSTNBR] [decimal](9, 0) NULL,
	[POSTSEQNCE] [decimal](9, 0) NULL,
	[SWJOB] [smallint] NULL,
	[SWRTG] [smallint] NULL,
	[SWRTGOUT] [smallint] NULL,
	[RTGDATEDUE] [decimal](9, 0) NULL,
	[RTGOAMTHC] [decimal](19, 3) NULL,
	[RTGAMTHC] [decimal](19, 3) NULL,
	[RTGOAMTTC] [decimal](19, 3) NULL,
	[RTGAMTTC] [decimal](19, 3) NULL,
	[RTGTERMS] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SWRTGRATE] [smallint] NULL,
	[RTGAPPLYTO] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VALUES] [int] NULL,
	[SRCEAPPL] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ARVERSION] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INVCTYPE] [smallint] NULL,
	[DEPSEQ] [int] NULL,
	[DEPLINE] [int] NULL,
	[TYPEBTCH] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CNTOBLJ] [int] NULL,
	[CODECURNRC] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RATERC] [decimal](15, 7) NULL,
	[RATETYPERC] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RATEDATERC] [decimal](9, 0) NULL,
	[RATEOPRC] [smallint] NULL,
	[SWRATERC] [smallint] NULL,
	[SWTXRTGRPT] [smallint] NULL,
	[CODETAXGRP] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TAXVERSION] [int] NULL,
	[SWTXCTLRC] [smallint] NULL,
	[TAXCLASS1] [smallint] NULL,
	[TAXCLASS2] [smallint] NULL,
	[TAXCLASS3] [smallint] NULL,
	[TAXCLASS4] [smallint] NULL,
	[TAXCLASS5] [smallint] NULL,
	[TXBSERT1TC] [decimal](19, 3) NULL,
	[TXBSERT2TC] [decimal](19, 3) NULL,
	[TXBSERT3TC] [decimal](19, 3) NULL,
	[TXBSERT4TC] [decimal](19, 3) NULL,
	[TXBSERT5TC] [decimal](19, 3) NULL,
	[TXAMTRT1TC] [decimal](19, 3) NULL,
	[TXAMTRT2TC] [decimal](19, 3) NULL,
	[TXAMTRT3TC] [decimal](19, 3) NULL,
	[TXAMTRT4TC] [decimal](19, 3) NULL,
	[TXAMTRT5TC] [decimal](19, 3) NULL,
	[IDSHIPNBR] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATEFRSTBK] [decimal](9, 0) NULL,
	[DATELSTRVL] [decimal](9, 0) NULL,
	[ORATE] [decimal](15, 7) NULL,
	[ORATETYPE] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORATEDATE] [decimal](9, 0) NULL,
	[ORATEOP] [smallint] NULL,
	[OSWRATE] [smallint] NULL,
	[IDACCTSET] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATEPAID] [decimal](9, 0) NULL,
	[SWNONRCVBL] [smallint] NULL,
	[CODETERR] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
