SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ARRRH](
	[IDBANK] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDCUST] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDRMIT] [char](24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEPSEQ] [int] NULL,
	[DEPLINE] [int] NULL,
	[DATERMIT] [decimal](9, 0) NULL,
	[AUDTDATE] [decimal](9, 0) NULL,
	[AUDTTIME] [decimal](9, 0) NULL,
	[AUDTUSER] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUDTORG] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEPSTNBR] [decimal](9, 0) NULL,
	[DATEBTCH] [decimal](9, 0) NULL,
	[AMTRMITTC] [decimal](19, 3) NULL,
	[AMTPAYM] [decimal](19, 3) NULL,
	[AMTDISC] [decimal](19, 3) NULL,
	[PAYMCODE] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODECURN] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDRATETYPE] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RATEEXCHHC] [decimal](15, 7) NULL,
	[SWOVRDRATE] [smallint] NULL,
	[TEXTRETRN] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATELSTMTN] [decimal](9, 0) NULL,
	[DATELSTSTM] [decimal](9, 0) NULL,
	[AMTROUNDER] [decimal](19, 3) NULL,
	[DATERATE] [decimal](9, 0) NULL,
	[FISCYR] [char](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FISCPER] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAMERMIT] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CNTBTCH] [decimal](9, 0) NULL,
	[CNTITEM] [decimal](7, 0) NULL,
	[SWCHKCLRD] [smallint] NULL,
	[AMTRMITHC] [decimal](19, 3) NULL,
	[AMTADJ] [decimal](19, 3) NULL,
	[DATECLRD] [decimal](9, 0) NULL,
	[DATERVRSD] [decimal](9, 0) NULL,
	[TRXTYPETXT] [smallint] NULL,
	[IDINVC] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RATEOP] [smallint] NULL,
	[PAYMTYPE] [smallint] NULL,
	[DRILLAPP] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRILLTYPE] [smallint] NULL,
	[DRILLDWNLK] [decimal](19, 0) NULL,
	[SWNONRCVBL] [smallint] NULL,
	[SWJOB] [smallint] NULL,
	[IDINVCMTCH] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SWTXAMTCTL] [smallint] NULL,
	[CODETAXGRP] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETAX1] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETAX2] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETAX3] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETAX4] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETAX5] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TAXCLASS1] [smallint] NULL,
	[TAXCLASS2] [smallint] NULL,
	[TAXCLASS3] [smallint] NULL,
	[TAXCLASS4] [smallint] NULL,
	[TAXCLASS5] [smallint] NULL,
	[TXBSE1TC] [decimal](19, 3) NULL,
	[TXBSE2TC] [decimal](19, 3) NULL,
	[TXBSE3TC] [decimal](19, 3) NULL,
	[TXBSE4TC] [decimal](19, 3) NULL,
	[TXBSE5TC] [decimal](19, 3) NULL,
	[TXAMT1TC] [decimal](19, 3) NULL,
	[TXAMT2TC] [decimal](19, 3) NULL,
	[TXAMT3TC] [decimal](19, 3) NULL,
	[TXAMT4TC] [decimal](19, 3) NULL,
	[TXAMT5TC] [decimal](19, 3) NULL,
	[TXTOTTC] [decimal](19, 3) NULL,
	[AMTNETTC] [decimal](19, 3) NULL,
	[CODECURNRC] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SWTXCTLRC] [smallint] NULL,
	[RATERC] [decimal](15, 7) NULL,
	[RATETYPERC] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RATEDATERC] [decimal](9, 0) NULL,
	[RATEOPRC] [smallint] NULL,
	[TXAMT1RC] [decimal](19, 3) NULL,
	[TXAMT2RC] [decimal](19, 3) NULL,
	[TXAMT3RC] [decimal](19, 3) NULL,
	[TXAMT4RC] [decimal](19, 3) NULL,
	[TXAMT5RC] [decimal](19, 3) NULL,
	[TXTOTRC] [decimal](19, 3) NULL,
	[TXBSE1HC] [decimal](19, 3) NULL,
	[TXBSE2HC] [decimal](19, 3) NULL,
	[TXBSE3HC] [decimal](19, 3) NULL,
	[TXBSE4HC] [decimal](19, 3) NULL,
	[TXBSE5HC] [decimal](19, 3) NULL,
	[TXAMT1HC] [decimal](19, 3) NULL,
	[TXAMT2HC] [decimal](19, 3) NULL,
	[TXAMT3HC] [decimal](19, 3) NULL,
	[TXAMT4HC] [decimal](19, 3) NULL,
	[TXAMT5HC] [decimal](19, 3) NULL,
	[TXTOTHC] [decimal](19, 3) NULL,
	[AMTNETHC] [decimal](19, 3) NULL,
	[CNTACC] [int] NULL,
	[AMTACCTC] [decimal](19, 3) NULL,
	[AMTACCHC] [decimal](19, 3) NULL,
	[DATEBUS] [decimal](9, 0) NULL,
	[CCTRANID] [char](36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PROCESSCOD] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
