SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ARIBH](
	[CNTBTCH] [decimal](9, 0) NULL,
	[CNTITEM] [decimal](7, 0) NULL,
	[AUDTDATE] [decimal](9, 0) NULL,
	[AUDTTIME] [decimal](9, 0) NULL,
	[AUDTUSER] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUDTORG] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDCUST] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDINVC] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDSHPT] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHIPVIA] [char](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPECINST] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TEXTTRX] [smallint] NULL,
	[IDTRX] [smallint] NULL,
	[INVCSTTS] [smallint] NULL,
	[ORDRNBR] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CUSTPO] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[JOBNBR] [char](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INVCDESC] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SWPRTINVC] [smallint] NULL,
	[INVCAPPLTO] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDACCTSET] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATEINVC] [decimal](9, 0) NULL,
	[DATEASOF] [decimal](9, 0) NULL,
	[FISCYR] [char](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FISCPER] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODECURN] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RATETYPE] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SWMANRTE] [smallint] NULL,
	[EXCHRATEHC] [decimal](15, 7) NULL,
	[ORIGRATEHC] [decimal](15, 7) NULL,
	[TERMCODE] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SWTERMOVRD] [smallint] NULL,
	[DATEDUE] [decimal](9, 0) NULL,
	[DATEDISC] [decimal](9, 0) NULL,
	[PCTDISC] [decimal](9, 5) NULL,
	[AMTDISCAVL] [decimal](19, 3) NULL,
	[LASTLINE] [decimal](5, 0) NULL,
	[CODESLSP1] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODESLSP2] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODESLSP3] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODESLSP4] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODESLSP5] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PCTSASPLT1] [decimal](9, 5) NULL,
	[PCTSASPLT2] [decimal](9, 5) NULL,
	[PCTSASPLT3] [decimal](9, 5) NULL,
	[PCTSASPLT4] [decimal](9, 5) NULL,
	[PCTSASPLT5] [decimal](9, 5) NULL,
	[SWTAXBL] [smallint] NULL,
	[SWMANTX] [smallint] NULL,
	[CODETAXGRP] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETAX1] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETAX2] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETAX3] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETAX4] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETAX5] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TAXSTTS1] [smallint] NULL,
	[TAXSTTS2] [smallint] NULL,
	[TAXSTTS3] [smallint] NULL,
	[TAXSTTS4] [smallint] NULL,
	[TAXSTTS5] [smallint] NULL,
	[BASETAX1] [decimal](19, 3) NULL,
	[BASETAX2] [decimal](19, 3) NULL,
	[BASETAX3] [decimal](19, 3) NULL,
	[BASETAX4] [decimal](19, 3) NULL,
	[BASETAX5] [decimal](19, 3) NULL,
	[AMTTAX1] [decimal](19, 3) NULL,
	[AMTTAX2] [decimal](19, 3) NULL,
	[AMTTAX3] [decimal](19, 3) NULL,
	[AMTTAX4] [decimal](19, 3) NULL,
	[AMTTAX5] [decimal](19, 3) NULL,
	[AMTTXBL] [decimal](19, 3) NULL,
	[AMTNOTTXBL] [decimal](19, 3) NULL,
	[AMTTAXTOT] [decimal](19, 3) NULL,
	[AMTINVCTOT] [decimal](19, 3) NULL,
	[AMTPPD] [decimal](19, 3) NULL,
	[AMTPAYMTOT] [decimal](5, 0) NULL,
	[AMTPYMSCHD] [decimal](19, 3) NULL,
	[AMTNETTOT] [decimal](19, 3) NULL,
	[IDSTDINVC] [char](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATEPRCS] [decimal](9, 0) NULL,
	[IDPPD] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDBILL] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHPTOLOC] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHPTOSTE1] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHPTOSTE2] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHPTOSTE3] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHPTOSTE4] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHPTOCITY] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHPTOSTTE] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHPTOPOST] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHPTOCTRY] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHPTOCTAC] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHPTOPHON] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHPTOFAX] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATERATE] [decimal](9, 0) NULL,
	[SWPROCPPD] [smallint] NULL,
	[CUROPER] [smallint] NULL,
	[DRILLAPP] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRILLTYPE] [smallint] NULL,
	[DRILLDWNLK] [decimal](19, 0) NULL,
	[SHPVIACODE] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHPVIADESC] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SWJOB] [smallint] NULL,
	[ERRBATCH] [int] NULL,
	[ERRENTRY] [int] NULL,
	[EMAIL] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CTACPHONE] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CTACFAX] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CTACEMAIL] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AMTDSBWTAX] [decimal](19, 3) NULL,
	[AMTDSBNTAX] [decimal](19, 3) NULL,
	[AMTDSCBASE] [decimal](19, 3) NULL,
	[INVCTYPE] [smallint] NULL,
	[SWRTGINVC] [smallint] NULL,
	[RTGAPPLYTO] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SWRTG] [smallint] NULL,
	[RTGAMT] [decimal](19, 3) NULL,
	[RTGPERCENT] [decimal](9, 5) NULL,
	[RTGDAYS] [smallint] NULL,
	[RTGDATEDUE] [decimal](9, 0) NULL,
	[RTGTERMS] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SWRTGDDTOV] [smallint] NULL,
	[SWRTGAMTOV] [smallint] NULL,
	[SWRTGRATE] [smallint] NULL,
	[VALUES] [int] NULL,
	[SRCEAPPL] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ARVERSION] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TAXVERSION] [int] NULL,
	[SWTXRTGRPT] [smallint] NULL,
	[CODECURNRC] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SWTXCTLRC] [smallint] NULL,
	[RATERC] [decimal](15, 7) NULL,
	[RATETYPERC] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RATEDATERC] [decimal](9, 0) NULL,
	[RATEOPRC] [smallint] NULL,
	[SWRATERC] [smallint] NULL,
	[TXAMT1RC] [decimal](19, 3) NULL,
	[TXAMT2RC] [decimal](19, 3) NULL,
	[TXAMT3RC] [decimal](19, 3) NULL,
	[TXAMT4RC] [decimal](19, 3) NULL,
	[TXAMT5RC] [decimal](19, 3) NULL,
	[TXTOTRC] [decimal](19, 3) NULL,
	[TXBSERT1TC] [decimal](19, 3) NULL,
	[TXBSERT2TC] [decimal](19, 3) NULL,
	[TXBSERT3TC] [decimal](19, 3) NULL,
	[TXBSERT4TC] [decimal](19, 3) NULL,
	[TXBSERT5TC] [decimal](19, 3) NULL,
	[TXAMTRT1TC] [decimal](19, 3) NULL,
	[TXAMTRT2TC] [decimal](19, 3) NULL,
	[TXAMTRT3TC] [decimal](19, 3) NULL,
	[TXAMTRT4TC] [decimal](19, 3) NULL,
	[TXAMTRT5TC] [decimal](19, 3) NULL,
	[TXBSE1HC] [decimal](19, 3) NULL,
	[TXBSE2HC] [decimal](19, 3) NULL,
	[TXBSE3HC] [decimal](19, 3) NULL,
	[TXBSE4HC] [decimal](19, 3) NULL,
	[TXBSE5HC] [decimal](19, 3) NULL,
	[TXAMT1HC] [decimal](19, 3) NULL,
	[TXAMT2HC] [decimal](19, 3) NULL,
	[TXAMT3HC] [decimal](19, 3) NULL,
	[TXAMT4HC] [decimal](19, 3) NULL,
	[TXAMT5HC] [decimal](19, 3) NULL,
	[AMTGROSHC] [decimal](19, 3) NULL,
	[RTGAMTHC] [decimal](19, 3) NULL,
	[AMTDISCHC] [decimal](19, 3) NULL,
	[DISTNETHC] [decimal](19, 3) NULL,
	[AMTPPDHC] [decimal](19, 3) NULL,
	[AMTDUEHC] [decimal](19, 3) NULL,
	[SWPRTLBL] [smallint] NULL,
	[IDSHIPNBR] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SWOECOST] [smallint] NULL,
	[ENTEREDBY] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATEBUS] [decimal](9, 0) NULL,
	[EDN] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
