SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ARCUS](
	[IDCUST] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUDTDATE] [decimal](9, 0) NULL,
	[AUDTTIME] [decimal](9, 0) NULL,
	[AUDTUSER] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUDTORG] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TEXTSNAM] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDGRP] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDNATACCT] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SWACTV] [smallint] NULL,
	[DATEINAC] [decimal](9, 0) NULL,
	[DATELASTMN] [decimal](9, 0) NULL,
	[SWHOLD] [smallint] NULL,
	[DATESTART] [decimal](9, 0) NULL,
	[IDPPNT] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODEDAB] [char](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODEDABRTG] [char](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATEDAB] [decimal](9, 0) NULL,
	[NAMECUST] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TEXTSTRE1] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TEXTSTRE2] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TEXTSTRE3] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TEXTSTRE4] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAMECITY] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODESTTE] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODEPSTL] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODECTRY] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAMECTAC] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TEXTPHON1] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TEXTPHON2] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETERR] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDACCTSET] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDAUTOCASH] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDBILLCYCL] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDSVCCHRG] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDDLNQ] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODECURN] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SWPRTSTMT] [smallint] NULL,
	[SWPRTDLNQ] [smallint] NULL,
	[SWBALFWD] [smallint] NULL,
	[CODETERM] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDRATETYPE] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETAXGRP] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDTAXREGI1] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDTAXREGI2] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDTAXREGI3] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDTAXREGI4] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDTAXREGI5] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TAXSTTS1] [smallint] NULL,
	[TAXSTTS2] [smallint] NULL,
	[TAXSTTS3] [smallint] NULL,
	[TAXSTTS4] [smallint] NULL,
	[TAXSTTS5] [smallint] NULL,
	[AMTCRLIMT] [decimal](19, 3) NULL,
	[AMTBALDUET] [decimal](19, 3) NULL,
	[AMTBALDUEH] [decimal](19, 3) NULL,
	[DATELASTST] [decimal](9, 0) NULL,
	[AMTLASTSTT] [decimal](19, 3) NULL,
	[AMTLASTSTH] [decimal](19, 3) NULL,
	[DTBEGBALFW] [decimal](9, 0) NULL,
	[AMTBALFWDT] [decimal](19, 3) NULL,
	[AMTBALFWDH] [decimal](19, 3) NULL,
	[DTLASTRVAL] [decimal](9, 0) NULL,
	[AMTBALLARV] [decimal](19, 3) NULL,
	[CNTOPENINV] [decimal](7, 0) NULL,
	[CNTINVPAID] [decimal](7, 0) NULL,
	[DAYSTOPAY] [decimal](7, 0) NULL,
	[DATEINVCHI] [decimal](9, 0) NULL,
	[DATEBALHI] [decimal](9, 0) NULL,
	[DATEINVHIL] [decimal](9, 0) NULL,
	[DATEBALHIL] [decimal](9, 0) NULL,
	[DATELASTAC] [decimal](9, 0) NULL,
	[DATELASTIV] [decimal](9, 0) NULL,
	[DATELASTCR] [decimal](9, 0) NULL,
	[DATELASTDR] [decimal](9, 0) NULL,
	[DATELASTPA] [decimal](9, 0) NULL,
	[DATELASTDI] [decimal](9, 0) NULL,
	[DATELASTAD] [decimal](9, 0) NULL,
	[DATELASTWR] [decimal](9, 0) NULL,
	[DATELASTRI] [decimal](9, 0) NULL,
	[DATELASTIN] [decimal](9, 0) NULL,
	[DATELASTDQ] [decimal](9, 0) NULL,
	[IDINVCHI] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDINVCHILY] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AMTINVHIT] [decimal](19, 3) NULL,
	[AMTBALHIT] [decimal](19, 3) NULL,
	[AMTINVHILT] [decimal](19, 3) NULL,
	[AMTBALHILT] [decimal](19, 3) NULL,
	[AMTLASTIVT] [decimal](19, 3) NULL,
	[AMTLASTCRT] [decimal](19, 3) NULL,
	[AMTLASTDRT] [decimal](19, 3) NULL,
	[AMTLASTPYT] [decimal](19, 3) NULL,
	[AMTLASTDIT] [decimal](19, 3) NULL,
	[AMTLASTADT] [decimal](19, 3) NULL,
	[AMTLASTWRT] [decimal](19, 3) NULL,
	[AMTLASTRIT] [decimal](19, 3) NULL,
	[AMTLASTINT] [decimal](19, 3) NULL,
	[AMTINVHIH] [decimal](19, 3) NULL,
	[AMTBALHIH] [decimal](19, 3) NULL,
	[AMTINVHILH] [decimal](19, 3) NULL,
	[AMTBALHILH] [decimal](19, 3) NULL,
	[AMTLASTIVH] [decimal](19, 3) NULL,
	[AMTLASTCRH] [decimal](19, 3) NULL,
	[AMTLASTDRH] [decimal](19, 3) NULL,
	[AMTLASTPYH] [decimal](19, 3) NULL,
	[AMTLASTDIH] [decimal](19, 3) NULL,
	[AMTLASTADH] [decimal](19, 3) NULL,
	[AMTLASTWRH] [decimal](19, 3) NULL,
	[AMTLASTRIH] [decimal](19, 3) NULL,
	[AMTLASTINH] [decimal](19, 3) NULL,
	[CODESLSP1] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODESLSP2] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODESLSP3] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODESLSP4] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODESLSP5] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PCTSASPLT1] [decimal](9, 5) NULL,
	[PCTSASPLT2] [decimal](9, 5) NULL,
	[PCTSASPLT3] [decimal](9, 5) NULL,
	[PCTSASPLT4] [decimal](9, 5) NULL,
	[PCTSASPLT5] [decimal](9, 5) NULL,
	[PRICLIST] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CUSTTYPE] [smallint] NULL,
	[AMTPDUE] [decimal](19, 3) NULL,
	[EMAIL1] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EMAIL2] [char](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WEBSITE] [char](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BILLMETHOD] [smallint] NULL,
	[PAYMCODE] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FOB] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHPVIACODE] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SHPVIADESC] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DELMETHOD] [smallint] NULL,
	[PRIMSHIPTO] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CTACPHONE] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CTACFAX] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SWPARTSHIP] [smallint] NULL,
	[SWWEBSHOP] [smallint] NULL,
	[RTGPERCENT] [decimal](9, 5) NULL,
	[RTGDAYS] [smallint] NULL,
	[RTGTERMS] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RTGAMTTC] [decimal](19, 3) NULL,
	[RTGAMTHC] [decimal](19, 3) NULL,
	[VALUES] [int] NULL,
	[CNTPPDINVC] [decimal](7, 0) NULL,
	[AMTPPDINVT] [decimal](19, 3) NULL,
	[AMTPPDINVH] [decimal](19, 3) NULL,
	[DATELASTRF] [decimal](9, 0) NULL,
	[AMTLASTRFT] [decimal](19, 3) NULL,
	[AMTLASTRFH] [decimal](19, 3) NULL,
	[CODECHECK] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NEXTCUID] [int] NULL,
	[LOCATION] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SWCHKLIMIT] [smallint] NULL,
	[SWCHKOVER] [smallint] NULL,
	[OVERDAYS] [smallint] NULL,
	[OVERAMT] [decimal](19, 3) NULL,
	[SWBACKORDR] [smallint] NULL,
	[SWCHKDUPPO] [smallint] NULL,
	[CATEGORY] [smallint] NULL,
	[BRN] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
