SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ARPYM](
	[IDCUST] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDINVC] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CNTSEQ] [int] NULL,
	[AUDTDATE] [decimal](9, 0) NULL,
	[AUDTTIME] [decimal](9, 0) NULL,
	[AUDTUSER] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUDTORG] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PAYMCODE] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PAYMTYPE] [smallint] NULL,
	[DOCDATE] [decimal](9, 0) NULL,
	[FISCYR] [char](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FISCPER] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDBANK] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CHECKNUM] [decimal](9, 0) NULL,
	[LONGSERIAL] [int] NULL,
	[IDACCT] [char](45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAMERMIT] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CHECKLANG] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODECURN] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RATETYPE] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RATEDATE] [decimal](9, 0) NULL,
	[RATEEXCH] [decimal](15, 7) NULL,
	[RATEOP] [smallint] NULL,
	[SWRATE] [smallint] NULL,
	[AMTPC] [decimal](19, 3) NULL,
	[AMTTC] [decimal](19, 3) NULL,
	[AMTHC] [decimal](19, 3) NULL,
	[POSTSEQNBR] [decimal](9, 0) NULL,
	[CNTBTCH] [decimal](9, 0) NULL,
	[CNTITEM] [decimal](7, 0) NULL,
	[SWSTATUS] [smallint] NULL,
	[DATECLRD] [decimal](9, 0) NULL,
	[DATERVRSD] [decimal](9, 0) NULL,
	[TEXTRETRN] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TRXTYPETXT] [smallint] NULL,
	[CUID] [int] NULL,
	[DATEBUS] [decimal](9, 0) NULL,
	[CCTRANID] [char](36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PROCESSCOD] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
