SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ARIBD_Staged](
	[CNTBTCH] [decimal](9, 0) NOT NULL,
	[CNTITEM] [decimal](7, 0) NOT NULL,
	[CNTLINE] [decimal](5, 0) NOT NULL,
	[AUDTDATE] [decimal](9, 0) NOT NULL,
	[AUDTTIME] [decimal](9, 0) NOT NULL,
	[AUDTUSER] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[AUDTORG] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[IDINVC] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[IDITEM] [char](16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[IDDIST] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TEXTDESC] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[SWMANLITEM] [smallint] NOT NULL,
	[UNITMEAS] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[QTYINVC] [decimal](19, 5) NOT NULL,
	[AMTCOST] [decimal](19, 6) NOT NULL,
	[AMTPRIC] [decimal](19, 6) NOT NULL,
	[AMTEXTN] [decimal](19, 3) NOT NULL,
	[AMTCOGS] [decimal](19, 3) NOT NULL,
	[AMTTXBL] [decimal](19, 3) NOT NULL,
	[TOTTAX] [decimal](19, 3) NOT NULL,
	[SWMANLTX] [smallint] NOT NULL,
	[BASETAX1] [decimal](19, 3) NOT NULL,
	[BASETAX2] [decimal](19, 3) NOT NULL,
	[BASETAX3] [decimal](19, 3) NOT NULL,
	[BASETAX4] [decimal](19, 3) NOT NULL,
	[BASETAX5] [decimal](19, 3) NOT NULL,
	[TAXSTTS1] [smallint] NOT NULL,
	[TAXSTTS2] [smallint] NOT NULL,
	[TAXSTTS3] [smallint] NOT NULL,
	[TAXSTTS4] [smallint] NOT NULL,
	[TAXSTTS5] [smallint] NOT NULL,
	[SWTAXINCL1] [smallint] NOT NULL,
	[SWTAXINCL2] [smallint] NOT NULL,
	[SWTAXINCL3] [smallint] NOT NULL,
	[SWTAXINCL4] [smallint] NOT NULL,
	[SWTAXINCL5] [smallint] NOT NULL,
	[RATETAX1] [decimal](15, 5) NOT NULL,
	[RATETAX2] [decimal](15, 5) NOT NULL,
	[RATETAX3] [decimal](15, 5) NOT NULL,
	[RATETAX4] [decimal](15, 5) NOT NULL,
	[RATETAX5] [decimal](15, 5) NOT NULL,
	[AMTTAX1] [decimal](19, 3) NOT NULL,
	[AMTTAX2] [decimal](19, 3) NOT NULL,
	[AMTTAX3] [decimal](19, 3) NOT NULL,
	[AMTTAX4] [decimal](19, 3) NOT NULL,
	[AMTTAX5] [decimal](19, 3) NOT NULL,
	[IDACCTREV] [char](45) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[IDACCTINV] [char](45) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[IDACCTCOGS] [char](45) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[IDJOBPROJ] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CONTRACT] [char](16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PROJECT] [char](16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CATEGORY] [char](16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[RESOURCE] [char](24) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TRANSNBR] [int] NOT NULL,
	[COSTCLASS] [smallint] NOT NULL,
	[BILLDATE] [decimal](9, 0) NOT NULL,
	[SWIBT] [smallint] NOT NULL,
	[SWDISCABL] [smallint] NOT NULL,
	[OCNTLINE] [decimal](5, 0) NOT NULL,
	[RTGAMT] [decimal](19, 3) NOT NULL,
	[RTGPERCENT] [decimal](9, 5) NOT NULL,
	[RTGDAYS] [smallint] NOT NULL,
	[RTGDATEDUE] [decimal](9, 0) NOT NULL,
	[SWRTGDDTOV] [smallint] NOT NULL,
	[SWRTGAMTOV] [smallint] NOT NULL,
	[VALUES] [int] NOT NULL,
	[RTGDISTTC] [decimal](19, 3) NOT NULL,
	[RTGCOGSTC] [decimal](19, 3) NOT NULL,
	[RTGALTBTC] [decimal](19, 3) NOT NULL,
	[RTGINVDIST] [decimal](19, 3) NOT NULL,
	[RTGINVCOGS] [decimal](19, 3) NOT NULL,
	[RTGINVALTB] [decimal](19, 3) NOT NULL,
	[TXAMT1RC] [decimal](19, 3) NOT NULL,
	[TXAMT2RC] [decimal](19, 3) NOT NULL,
	[TXAMT3RC] [decimal](19, 3) NOT NULL,
	[TXAMT4RC] [decimal](19, 3) NOT NULL,
	[TXAMT5RC] [decimal](19, 3) NOT NULL,
	[TXTOTRC] [decimal](19, 3) NOT NULL,
	[TXBSERT1TC] [decimal](19, 3) NOT NULL,
	[TXBSERT2TC] [decimal](19, 3) NOT NULL,
	[TXBSERT3TC] [decimal](19, 3) NOT NULL,
	[TXBSERT4TC] [decimal](19, 3) NOT NULL,
	[TXBSERT5TC] [decimal](19, 3) NOT NULL,
	[TXAMTRT1TC] [decimal](19, 3) NOT NULL,
	[TXAMTRT2TC] [decimal](19, 3) NOT NULL,
	[TXAMTRT3TC] [decimal](19, 3) NOT NULL,
	[TXAMTRT4TC] [decimal](19, 3) NOT NULL,
	[TXAMTRT5TC] [decimal](19, 3) NOT NULL,
	[TXBSE1HC] [decimal](19, 3) NOT NULL,
	[TXBSE2HC] [decimal](19, 3) NOT NULL,
	[TXBSE3HC] [decimal](19, 3) NOT NULL,
	[TXBSE4HC] [decimal](19, 3) NOT NULL,
	[TXBSE5HC] [decimal](19, 3) NOT NULL,
	[TXAMT1HC] [decimal](19, 3) NOT NULL,
	[TXAMT2HC] [decimal](19, 3) NOT NULL,
	[TXAMT3HC] [decimal](19, 3) NOT NULL,
	[TXAMT4HC] [decimal](19, 3) NOT NULL,
	[TXAMT5HC] [decimal](19, 3) NOT NULL,
	[TXAMTRT1HC] [decimal](19, 3) NOT NULL,
	[TXAMTRT2HC] [decimal](19, 3) NOT NULL,
	[TXAMTRT3HC] [decimal](19, 3) NOT NULL,
	[TXAMTRT4HC] [decimal](19, 3) NOT NULL,
	[TXAMTRT5HC] [decimal](19, 3) NOT NULL,
	[DISTNETHC] [decimal](19, 3) NOT NULL,
	[RTGAMTHC] [decimal](19, 3) NOT NULL,
	[AMTCOGSHC] [decimal](19, 3) NOT NULL,
	[AMTCOSTHC] [decimal](19, 6) NOT NULL,
	[AMTPRICHC] [decimal](19, 6) NOT NULL,
	[AMTEXTNHC] [decimal](19, 3) NOT NULL,
	[EDN] [char](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]

GO
