SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ARCUSO_Staged](
	[IDCUST] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[OPTFIELD] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[AUDTDATE] [decimal](9, 0) NOT NULL,
	[AUDTTIME] [decimal](9, 0) NOT NULL,
	[AUDTUSER] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[AUDTORG] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[VALUE] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TYPE] [smallint] NOT NULL,
	[LENGTH] [smallint] NOT NULL,
	[DECIMALS] [smallint] NOT NULL,
	[ALLOWNULL] [smallint] NOT NULL,
	[VALIDATE] [smallint] NOT NULL,
	[SWSET] [smallint] NOT NULL
) ON [PRIMARY]

GO
