SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ARPYM_Staged](
	[IDCUST] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[IDINVC] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CNTSEQ] [int] NOT NULL,
	[AUDTDATE] [decimal](9, 0) NOT NULL,
	[AUDTTIME] [decimal](9, 0) NOT NULL,
	[AUDTUSER] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[AUDTORG] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PAYMCODE] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PAYMTYPE] [smallint] NOT NULL,
	[DOCDATE] [decimal](9, 0) NOT NULL,
	[FISCYR] [char](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FISCPER] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[IDBANK] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CHECKNUM] [decimal](9, 0) NOT NULL,
	[LONGSERIAL] [int] NOT NULL,
	[IDACCT] [char](45) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[NAMERMIT] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CHECKLANG] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CODECURN] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[RATETYPE] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[RATEDATE] [decimal](9, 0) NOT NULL,
	[RATEEXCH] [decimal](15, 7) NOT NULL,
	[RATEOP] [smallint] NOT NULL,
	[SWRATE] [smallint] NOT NULL,
	[AMTPC] [decimal](19, 3) NOT NULL,
	[AMTTC] [decimal](19, 3) NOT NULL,
	[AMTHC] [decimal](19, 3) NOT NULL,
	[POSTSEQNBR] [decimal](9, 0) NOT NULL,
	[CNTBTCH] [decimal](9, 0) NOT NULL,
	[CNTITEM] [decimal](7, 0) NOT NULL,
	[SWSTATUS] [smallint] NOT NULL,
	[DATECLRD] [decimal](9, 0) NOT NULL,
	[DATERVRSD] [decimal](9, 0) NOT NULL,
	[TEXTRETRN] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TRXTYPETXT] [smallint] NOT NULL,
	[CUID] [int] NOT NULL,
	[DATEBUS] [decimal](9, 0) NOT NULL,
	[CCTRANID] [char](36) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PROCESSCOD] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]

GO
