SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ARTCR](
	[CODEPYMTYP] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CNTBTCH] [decimal](9, 0) NULL,
	[CNTITEM] [decimal](7, 0) NULL,
	[AUDTDATE] [decimal](9, 0) NULL,
	[AUDTTIME] [decimal](9, 0) NULL,
	[AUDTUSER] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUDTORG] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDRMIT] [char](24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDCUST] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATERMIT] [decimal](9, 0) NULL,
	[TEXTRMIT] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TXTRMITREF] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AMTRMIT] [decimal](19, 3) NULL,
	[AMTRMITTC] [decimal](19, 3) NULL,
	[RATEEXCHTC] [decimal](15, 7) NULL,
	[SWRATETC] [smallint] NULL,
	[CNTPAYMETR] [decimal](5, 0) NULL,
	[AMTPAYMTC] [decimal](19, 3) NULL,
	[AMTDISCTC] [decimal](19, 3) NULL,
	[CODEPAYM] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODECURN] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RATETYPEHC] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RATEEXCHHC] [decimal](15, 7) NULL,
	[SWRATEHC] [smallint] NULL,
	[RMITTYPE] [smallint] NULL,
	[DOCTYPE] [smallint] NULL,
	[IDINVCMTCH] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CNTLSTLINE] [decimal](5, 0) NULL,
	[FISCYR] [char](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FISCPER] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TEXTPAYOR] [char](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATERATETC] [decimal](9, 0) NULL,
	[RATETYPETC] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AMTADJENT] [decimal](19, 3) NULL,
	[DATERATEHC] [decimal](9, 0) NULL,
	[PAYMTYPE] [smallint] NULL,
	[REMUNAPLTC] [decimal](19, 3) NULL,
	[REMUNAPL] [decimal](19, 3) NULL,
	[AMTRMITHC] [decimal](19, 3) NULL,
	[DOCNBR] [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AMTADJHC] [decimal](19, 3) NULL,
	[OPERBANK] [smallint] NULL,
	[OPERCUST] [smallint] NULL,
	[AMTDISCHC] [decimal](19, 3) NULL,
	[AMTDBADJHC] [decimal](19, 3) NULL,
	[AMTCRADJHC] [decimal](19, 3) NULL,
	[AMTDBADJTC] [decimal](19, 3) NULL,
	[AMTCRADJTC] [decimal](19, 3) NULL,
	[SWJOB] [smallint] NULL,
	[APPLYMETH] [smallint] NULL,
	[ERRBATCH] [int] NULL,
	[ERRENTRY] [int] NULL,
	[VALUES] [int] NULL,
	[SRCEAPPL] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDBANK] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODECURNBC] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRILLAPP] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRILLTYPE] [smallint] NULL,
	[DRILLDWNLK] [decimal](19, 0) NULL,
	[SWPRINTED] [smallint] NULL,
	[SWTXAMTCTL] [smallint] NULL,
	[CODETAXGRP] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TAXVERSION] [int] NULL,
	[CODETAX1] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETAX2] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETAX3] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETAX4] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CODETAX5] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TAXCLASS1] [smallint] NULL,
	[TAXCLASS2] [smallint] NULL,
	[TAXCLASS3] [smallint] NULL,
	[TAXCLASS4] [smallint] NULL,
	[TAXCLASS5] [smallint] NULL,
	[TXBSE1TC] [decimal](19, 3) NULL,
	[TXBSE2TC] [decimal](19, 3) NULL,
	[TXBSE3TC] [decimal](19, 3) NULL,
	[TXBSE4TC] [decimal](19, 3) NULL,
	[TXBSE5TC] [decimal](19, 3) NULL,
	[TXAMT1TC] [decimal](19, 3) NULL,
	[TXAMT2TC] [decimal](19, 3) NULL,
	[TXAMT3TC] [decimal](19, 3) NULL,
	[TXAMT4TC] [decimal](19, 3) NULL,
	[TXAMT5TC] [decimal](19, 3) NULL,
	[TXTOTTC] [decimal](19, 3) NULL,
	[AMTNETTC] [decimal](19, 3) NULL,
	[DEPSEQ] [int] NULL,
	[DEPLINE] [int] NULL,
	[CODECURNRC] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SWTXCTLRC] [smallint] NULL,
	[RATERC] [decimal](15, 7) NULL,
	[RATETYPERC] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RATEDATERC] [decimal](9, 0) NULL,
	[RATEOPRC] [smallint] NULL,
	[SWRATERC] [smallint] NULL,
	[TXAMT1RC] [decimal](19, 3) NULL,
	[TXAMT2RC] [decimal](19, 3) NULL,
	[TXAMT3RC] [decimal](19, 3) NULL,
	[TXAMT4RC] [decimal](19, 3) NULL,
	[TXAMT5RC] [decimal](19, 3) NULL,
	[TXTOTRC] [decimal](19, 3) NULL,
	[CNTACC] [int] NULL,
	[AMTACCTC] [decimal](19, 3) NULL,
	[AMTACCHC] [decimal](19, 3) NULL,
	[AMTPAYMHC] [decimal](19, 3) NULL,
	[REMUNAPLHC] [decimal](19, 3) NULL,
	[TXBSE1HC] [decimal](19, 3) NULL,
	[TXBSE2HC] [decimal](19, 3) NULL,
	[TXBSE3HC] [decimal](19, 3) NULL,
	[TXBSE4HC] [decimal](19, 3) NULL,
	[TXBSE5HC] [decimal](19, 3) NULL,
	[TXAMT1HC] [decimal](19, 3) NULL,
	[TXAMT2HC] [decimal](19, 3) NULL,
	[TXAMT3HC] [decimal](19, 3) NULL,
	[TXAMT4HC] [decimal](19, 3) NULL,
	[TXAMT5HC] [decimal](19, 3) NULL,
	[TXTOTHC] [decimal](19, 3) NULL,
	[AMTNETHC] [decimal](19, 3) NULL,
	[ARVERSION] [char](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENTEREDBY] [char](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DATEBUS] [decimal](9, 0) NULL,
	[IDACCTSET] [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCPREVID] [char](36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCPREVSTTS] [smallint] NULL,
	[CCTRANID] [char](36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCTRANSTTS] [smallint] NULL,
	[PROCESSCOD] [char](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
