SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PARADES](
	[MST_SQ] [int] NULL,
	[PAR_DATE] [datetime] NULL,
	[PT_CODEID] [smallint] NULL,
	[PAR_MSG] [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WL_CODEID] [smallint] NULL,
	[PAR_CATEGORY] [smallint] NULL
) ON [PRIMARY]

GO
