SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [PROD1].[SORDERQ](
	[UPDTICK_0] [int] NULL,
	[SOHNUM_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SOPLIN_0] [int] NULL,
	[SOQSEQ_0] [int] NULL,
	[CPY_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SOHCAT_0] [tinyint] NULL,
	[SALFCY_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BPCORD_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BPAADD_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ITMREF_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ECCVALMAJ_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ECCVALMIN_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STOFCY_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[USEPLC_0] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CAD_0] [tinyint] NULL,
	[YEA_0] [smallint] NULL,
	[MON_0] [smallint] NULL,
	[DLVDAY_0] [smallint] NULL,
	[WEE_0] [smallint] NULL,
	[ORDDAT_0] [datetime] NULL,
	[DEMDLVDAT_0] [datetime] NULL,
	[DEMDLVHOU_0] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAXDLVHOU_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAXDLVDAT_0] [datetime] NULL,
	[DEMDLVREF_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IMPNUMLIG_0] [int] NULL,
	[SHIDAT_0] [datetime] NULL,
	[SHIHOU_0] [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXTDLVDAT_0] [datetime] NULL,
	[SOQSTA_0] [tinyint] NULL,
	[INVFLG_0] [tinyint] NULL,
	[DEMSTA_0] [tinyint] NULL,
	[DEMNUM_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STOMGTCOD_0] [tinyint] NULL,
	[LOT_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STA_0] [nvarchar](24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOC_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ALLTYP_0] [tinyint] NULL,
	[DSPLINFLG_0] [tinyint] NULL,
	[DDTANUM_0] [smallint] NULL,
	[DDTANUM_1] [smallint] NULL,
	[DDTANUM_2] [smallint] NULL,
	[DDTANUM_3] [smallint] NULL,
	[DDTANUM_4] [smallint] NULL,
	[DDTANUM_5] [smallint] NULL,
	[DDTANUM_6] [smallint] NULL,
	[DDTANUM_7] [smallint] NULL,
	[DDTANUM_8] [smallint] NULL,
	[DDTANOT_0] [numeric](27, 13) NULL,
	[DDTANOT_1] [numeric](27, 13) NULL,
	[DDTANOT_2] [numeric](27, 13) NULL,
	[DDTANOT_3] [numeric](27, 13) NULL,
	[DDTANOT_4] [numeric](27, 13) NULL,
	[DDTANOT_5] [numeric](27, 13) NULL,
	[DDTANOT_6] [numeric](27, 13) NULL,
	[DDTANOT_7] [numeric](27, 13) NULL,
	[DDTANOT_8] [numeric](27, 13) NULL,
	[ORIQTY_0] [numeric](28, 13) NULL,
	[QTY_0] [numeric](28, 13) NULL,
	[SHTQTY_0] [numeric](28, 13) NULL,
	[ALLQTY_0] [numeric](28, 13) NULL,
	[ODLQTY_0] [numeric](28, 13) NULL,
	[DLVQTY_0] [numeric](28, 13) NULL,
	[INVQTY_0] [numeric](28, 13) NULL,
	[TDLQTY_0] [numeric](28, 13) NULL,
	[LPRQTY_0] [numeric](28, 13) NULL,
	[OPRQTY_0] [numeric](28, 13) NULL,
	[PREQTY_0] [numeric](28, 13) NULL,
	[QTYSTU_0] [numeric](28, 13) NULL,
	[SHTQTYSTU_0] [numeric](28, 13) NULL,
	[ALLQTYSTU_0] [numeric](28, 13) NULL,
	[ODLQTYSTU_0] [numeric](28, 13) NULL,
	[DLVQTYSTU_0] [numeric](28, 13) NULL,
	[INVQTYSTU_0] [numeric](28, 13) NULL,
	[TDLQTYSTU_0] [numeric](28, 13) NULL,
	[LPRQTYSTU_0] [numeric](28, 13) NULL,
	[OPRQTYSTU_0] [numeric](28, 13) NULL,
	[PREQTYSTU_0] [numeric](28, 13) NULL,
	[PRECOD_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DRN_0] [tinyint] NULL,
	[DLVPIO_0] [tinyint] NULL,
	[DLVPIOCMP_0] [smallint] NULL,
	[BPTNUM_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MDL_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DAYLTI_0] [smallint] NULL,
	[PCK_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PCKCAP_0] [numeric](18, 7) NULL,
	[SOQTEX_0] [nvarchar](24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SDHNUM_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SDDLIN_0] [int] NULL,
	[FMI_0] [tinyint] NULL,
	[FMINUM_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FMILIN_0] [int] NULL,
	[FMISEQ_0] [int] NULL,
	[POHNUM_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POPLIN_0] [int] NULL,
	[POQSEQ_0] [int] NULL,
	[PERSTRDAT_0] [datetime] NULL,
	[PERENDDAT_0] [datetime] NULL,
	[PERNBRDAY_0] [smallint] NULL,
	[GEOCOD_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INSCTYFLG_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VTS_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VTC_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TAXGEOFLG_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TAXFLG_0] [smallint] NULL,
	[TAXREGFLG_0] [smallint] NULL,
	[RATTAXLIN_0] [numeric](28, 8) NULL,
	[BASTAXLIN_0] [numeric](28, 8) NULL,
	[XCOST_0] [numeric](14, 3) NULL,
	[OCNPRNBOM_0] [tinyint] NULL,
	[NDEPRNBOM_0] [tinyint] NULL,
	[XSTAGE_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INVPRNBOM_0] [tinyint] NULL,
	[CCLREN_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[XLINE_0] [int] NULL,
	[CCLDAT_0] [datetime] NULL,
	[PITFLG_0] [numeric](28, 13) NULL,
	[XUOM_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXPNUM_0] [int] NULL,
	[DSPLINWEI_0] [numeric](28, 13) NULL,
	[DSPLINVOL_0] [numeric](28, 13) NULL,
	[DSPWEU_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DSPVOU_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PJT_0] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LINORDNUM_0] [smallint] NULL,
	[USELIMDAT_0] [datetime] NULL,
	[CREUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CREDAT_0] [datetime] NULL,
	[UPDUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDDAT_0] [datetime] NULL,
	[CREDATTIM_0] [datetime] NULL,
	[UPDDATTIM_0] [datetime] NULL,
	[AUUID_0] [binary](16) NULL,
	[DLVFLG_0] [tinyint] NULL,
	[INVAMT_0] [numeric](27, 13) NULL,
	[SOQPSONUM_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SOQSEQNUM_0] [smallint] NULL,
	[ROWID] [numeric](38, 0) NULL
) ON [PRIMARY]

GO
