SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [PROD1].[COMPANY](
	[UPDTICK_0] [int] NULL,
	[CPY_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPYNAM_0] [nvarchar](70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPYSHO_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPYLEGFLG_0] [tinyint] NULL,
	[LEG_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACM_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAIFCY_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CRY_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CRN_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAF_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NID_0] [nvarchar](160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPYLOG_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RGCAMT_0] [numeric](20, 5) NULL,
	[RGCCUR_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BPAADD_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CNTNAM_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BIDNUM_0] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACCCOD_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIVCOD_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EECNUM_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CREDAT_0] [datetime] NULL,
	[CREUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDDAT_0] [datetime] NULL,
	[UPDUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STRPER_0] [datetime] NULL,
	[ACCCUR_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CREDATTIM_0] [datetime] NULL,
	[UPDDATTIM_0] [datetime] NULL,
	[AUUID_0] [binary](16) NULL,
	[DIE_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_1] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_2] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_3] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_4] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_5] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_6] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_7] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_8] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_9] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_10] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_11] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_12] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_13] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_14] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_15] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_16] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_17] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_18] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_19] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KACT_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NUMADD_0] [smallint] NULL,
	[OBYDIE_0] [tinyint] NULL,
	[OBYDIE_1] [tinyint] NULL,
	[OBYDIE_2] [tinyint] NULL,
	[OBYDIE_3] [tinyint] NULL,
	[OBYDIE_4] [tinyint] NULL,
	[OBYDIE_5] [tinyint] NULL,
	[OBYDIE_6] [tinyint] NULL,
	[OBYDIE_7] [tinyint] NULL,
	[OBYDIE_8] [tinyint] NULL,
	[OBYDIE_9] [tinyint] NULL,
	[OBYDIE_10] [tinyint] NULL,
	[OBYDIE_11] [tinyint] NULL,
	[OBYDIE_12] [tinyint] NULL,
	[OBYDIE_13] [tinyint] NULL,
	[OBYDIE_14] [tinyint] NULL,
	[OBYDIE_15] [tinyint] NULL,
	[OBYDIE_16] [tinyint] NULL,
	[OBYDIE_17] [tinyint] NULL,
	[OBYDIE_18] [tinyint] NULL,
	[OBYDIE_19] [tinyint] NULL,
	[STAFED_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DACDIE_0] [tinyint] NULL,
	[DACDIE_1] [tinyint] NULL,
	[DACDIE_2] [tinyint] NULL,
	[DACDIE_3] [tinyint] NULL,
	[DACDIE_4] [tinyint] NULL,
	[DACDIE_5] [tinyint] NULL,
	[DACDIE_6] [tinyint] NULL,
	[DACDIE_7] [tinyint] NULL,
	[DACDIE_8] [tinyint] NULL,
	[DACDIE_9] [tinyint] NULL,
	[DACDIE_10] [tinyint] NULL,
	[DACDIE_11] [tinyint] NULL,
	[DACDIE_12] [tinyint] NULL,
	[DACDIE_13] [tinyint] NULL,
	[DACDIE_14] [tinyint] NULL,
	[DACDIE_15] [tinyint] NULL,
	[DACDIE_16] [tinyint] NULL,
	[DACDIE_17] [tinyint] NULL,
	[DACDIE_18] [tinyint] NULL,
	[DACDIE_19] [tinyint] NULL,
	[GRUCOD_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_1] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_2] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_3] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_4] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_5] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_6] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_7] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_8] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_9] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_10] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_11] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_12] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_13] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_14] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_15] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_16] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_17] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_18] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_19] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PLISTC_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RTZFLG_0] [smallint] NULL,
	[AGTPCP_0] [smallint] NULL,
	[VACCPY_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DCLDIRBALPAY_0] [tinyint] NULL,
	[ZOVRPTHFLG_0] [tinyint] NULL,
	[BDFECOCOD_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AUSFINSRV_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GERDEFVAL_0] [smallint] NULL,
	[GEREECNUM_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GERTAXCEN_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GERTAXIDT_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GERCODELMA5_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GERPTP_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SPABPCTSD_0] [numeric](28, 8) NULL,
	[SPABPSTSD_0] [numeric](28, 8) NULL,
	[SPAYEATSD_0] [numeric](28, 8) NULL,
	[PORCTFACN_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PORCPYACT_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PORDCLPER_0] [smallint] NULL,
	[PORLRC_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PORHQR_0] [smallint] NULL,
	[PORCPYACTDET_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PORFINDPR_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCINUM_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PORCPYACTTYP_0] [smallint] NULL,
	[PORSIMINVISS_0] [smallint] NULL,
	[PORAMTSERINV_0] [numeric](28, 8) NULL,
	[PORAMTITMINV_0] [numeric](28, 8) NULL,
	[PORRESFISCDA_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SSTTAXACT_0] [smallint] NULL,
	[SSTCPY_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SFINUM_0] [smallint] NULL,
	[COMMTYPE_0] [smallint] NULL,
	[STRDAT_0] [datetime] NULL,
	[ENDDAT_0] [datetime] NULL,
	[ROWID] [numeric](38, 0) NULL
) ON [PRIMARY]

GO
