SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [PROD1].[PREQUIS](
	[UPDTICK_0] [int] NULL,
	[PSHNUM_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPY_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PSHFCY_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRQDAT_0] [datetime] NULL,
	[DIE_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_1] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_2] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_3] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_4] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_5] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_6] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_7] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_8] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_9] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_10] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_11] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_12] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_13] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_14] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_15] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_16] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_17] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_18] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_19] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_1] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_2] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_3] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_4] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_5] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_6] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_7] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_8] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_9] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_10] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_11] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_12] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_13] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_14] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_15] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_16] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_17] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_18] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_19] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PJTH_0] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LINNBR_0] [smallint] NULL,
	[FBULINNBR_0] [smallint] NULL,
	[APPLINNBR_0] [smallint] NULL,
	[ORDLINNBR_0] [smallint] NULL,
	[CLELINNBR_0] [smallint] NULL,
	[APPFLG_0] [tinyint] NULL,
	[ORDFLG_0] [tinyint] NULL,
	[CLEFLG_0] [tinyint] NULL,
	[PRNFLG_0] [tinyint] NULL,
	[TEX1_0] [nvarchar](24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TEX2_0] [nvarchar](24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REQUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TOTPRQ_0] [numeric](27, 13) NULL,
	[PSHNUMMMS_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MMSURL_0] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXPNUM_0] [int] NULL,
	[CREUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CREDAT_0] [datetime] NULL,
	[UPDUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDDAT_0] [datetime] NULL,
	[CREDATTIM_0] [datetime] NULL,
	[ZPOTXTYPE_0] [tinyint] NULL,
	[UPDDATTIM_0] [datetime] NULL,
	[AUUID_0] [binary](16) NULL,
	[ZREQDUSR_0] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ATECORI_0] [tinyint] NULL,
	[ZREQDESC_0] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZBPSNUM_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZQUOTE_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[XHDSA_0] [real] NULL,
	[XCONTRACT_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[XSTOCKPILE_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[XSTAGE_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZMRQS_0] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZSAQ_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZPROC_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ROWID] [numeric](38, 0) NULL
) ON [PRIMARY]

GO
