SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [PROD1].[CPTANALIN](
	[UPDTICK_0] [int] NULL,
	[ABRFIC_0] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VCRTYP_0] [tinyint] NULL,
	[VCRNUM_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VCRLIN_0] [int] NULL,
	[VCRSEQ_0] [int] NULL,
	[CPLCLE_0] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ANALIG_0] [smallint] NULL,
	[LED_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LED_1] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LED_2] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LED_3] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LED_4] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LED_5] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LED_6] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LED_7] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LED_8] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LED_9] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COA_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COA_1] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COA_2] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COA_3] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COA_4] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COA_5] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COA_6] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COA_7] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COA_8] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COA_9] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACC_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACC_1] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACC_2] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACC_3] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACC_4] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACC_5] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACC_6] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACC_7] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACC_8] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACC_9] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DSP_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_1] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_2] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_3] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_4] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_5] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_6] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_7] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_8] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_9] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_10] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_11] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_12] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_13] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_14] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_15] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_16] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_17] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_18] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_19] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_1] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_2] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_3] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_4] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_5] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_6] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_7] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_8] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_9] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_10] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_11] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_12] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_13] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_14] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_15] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_16] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_17] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_18] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_19] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GLU_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QTY_0] [numeric](28, 13) NULL,
	[CUR_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AMT_0] [numeric](27, 13) NULL,
	[CREDATTIM_0] [datetime] NULL,
	[UPDDATTIM_0] [datetime] NULL,
	[AUUID_0] [binary](16) NULL,
	[CREUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ROWID] [numeric](38, 0) NULL
) ON [PRIMARY]

GO
