SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [PROD1].[GACCENTRYA](
	[UPDTICK_0] [int] NULL,
	[TYP_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NUM_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LIN_0] [smallint] NULL,
	[LEDTYP_0] [tinyint] NULL,
	[ANALIN_0] [smallint] NULL,
	[IDTLIN_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LED_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPY_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FCYLIN_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACCDAT_0] [datetime] NULL,
	[ACCNUM_0] [int] NULL,
	[COA_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACC_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BPR_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_1] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_2] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_3] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_4] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_5] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_6] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_7] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_8] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_1] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_2] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_3] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_4] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_5] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_6] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_7] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCE_8] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SNS_0] [smallint] NULL,
	[CUR_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AMTCUR_0] [numeric](27, 13) NULL,
	[CURLED_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AMTLED_0] [numeric](27, 13) NULL,
	[UOM_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QTY_0] [numeric](28, 13) NULL,
	[ACCNUMDOE_0] [int] NULL,
	[CREDATTIM_0] [datetime] NULL,
	[UPDDATTIM_0] [datetime] NULL,
	[AUUID_0] [binary](16) NULL,
	[CREUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ROWID] [numeric](38, 0) NULL
) ON [PRIMARY]

GO
