SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [PROD1].[GACCOUNT](
	[UPDTICK_0] [int] NULL,
	[COA_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACC_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DES_0] [nvarchar](360) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DESSHO_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DESTRA_0] [nvarchar](360) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SAC_0] [tinyint] NULL,
	[ACCSHO_0] [nvarchar](24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CSLDEB_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CSLCDT_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CSLFLG_0] [tinyint] NULL,
	[CSLFLGFLW_0] [tinyint] NULL,
	[FLODEB_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FLOCDT_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLSCOD_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CUR_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SUBACC_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SUBBPR_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODDEB_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODDEB_1] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODDEB_2] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODDEB_3] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODDEB_4] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODDEB_5] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODDEB_6] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODDEB_7] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODDEB_8] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODDEB_9] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODCDT_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODCDT_1] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODCDT_2] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODCDT_3] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODCDT_4] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODCDT_5] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODCDT_6] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODCDT_7] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODCDT_8] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RPTCODCDT_9] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FLGUOM_0] [tinyint] NULL,
	[UOM_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VALUOM_0] [numeric](21, 10) NULL,
	[ENAFLG_0] [tinyint] NULL,
	[ACS_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FCY_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VLYSTR_0] [datetime] NULL,
	[VLYEND_0] [datetime] NULL,
	[AUZ_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COANBR_0] [smallint] NULL,
	[OTHCOA_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_1] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_2] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_3] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_4] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_5] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_6] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_7] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_8] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_9] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_10] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_11] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_12] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_13] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_14] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_15] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_16] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_17] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_18] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_19] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_20] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_21] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_22] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_23] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_24] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_25] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_26] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_27] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_28] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_29] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_30] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_31] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_32] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_33] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_34] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_35] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_36] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_37] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_38] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_39] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_40] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_41] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_42] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_43] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_44] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_45] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_46] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_47] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_48] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHCOA_49] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_1] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_2] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_3] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_4] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_5] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_6] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_7] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_8] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_9] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_10] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_11] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_12] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_13] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_14] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_15] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_16] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_17] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_18] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_19] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_20] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_21] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_22] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_23] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_24] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_25] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_26] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_27] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_28] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_29] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_30] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_31] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_32] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_33] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_34] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_35] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_36] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_37] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_38] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_39] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_40] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_41] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_42] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_43] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_44] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_45] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_46] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_47] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_48] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFACC_49] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_1] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_2] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_3] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_4] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_5] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_6] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_7] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_8] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_9] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_10] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_11] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_12] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_13] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_14] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_15] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_16] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_17] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_18] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_19] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_20] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_21] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_22] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_23] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_24] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_25] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_26] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_27] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_28] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_29] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_30] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_31] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_32] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_33] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_34] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_35] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_36] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_37] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_38] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_39] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_40] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_41] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_42] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_43] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_44] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_45] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_46] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_47] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_48] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SCRACC_49] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OBYIPT_0] [tinyint] NULL,
	[OBYIPT_1] [tinyint] NULL,
	[OBYIPT_2] [tinyint] NULL,
	[OBYIPT_3] [tinyint] NULL,
	[OBYIPT_4] [tinyint] NULL,
	[OBYIPT_5] [tinyint] NULL,
	[OBYIPT_6] [tinyint] NULL,
	[OBYIPT_7] [tinyint] NULL,
	[OBYIPT_8] [tinyint] NULL,
	[OBYIPT_9] [tinyint] NULL,
	[OBYIPT_10] [tinyint] NULL,
	[OBYIPT_11] [tinyint] NULL,
	[OBYIPT_12] [tinyint] NULL,
	[OBYIPT_13] [tinyint] NULL,
	[OBYIPT_14] [tinyint] NULL,
	[OBYIPT_15] [tinyint] NULL,
	[OBYIPT_16] [tinyint] NULL,
	[OBYIPT_17] [tinyint] NULL,
	[OBYIPT_18] [tinyint] NULL,
	[OBYIPT_19] [tinyint] NULL,
	[OBYIPT_20] [tinyint] NULL,
	[OBYIPT_21] [tinyint] NULL,
	[OBYIPT_22] [tinyint] NULL,
	[OBYIPT_23] [tinyint] NULL,
	[OBYIPT_24] [tinyint] NULL,
	[OBYIPT_25] [tinyint] NULL,
	[OBYIPT_26] [tinyint] NULL,
	[OBYIPT_27] [tinyint] NULL,
	[OBYIPT_28] [tinyint] NULL,
	[OBYIPT_29] [tinyint] NULL,
	[OBYIPT_30] [tinyint] NULL,
	[OBYIPT_31] [tinyint] NULL,
	[OBYIPT_32] [tinyint] NULL,
	[OBYIPT_33] [tinyint] NULL,
	[OBYIPT_34] [tinyint] NULL,
	[OBYIPT_35] [tinyint] NULL,
	[OBYIPT_36] [tinyint] NULL,
	[OBYIPT_37] [tinyint] NULL,
	[OBYIPT_38] [tinyint] NULL,
	[OBYIPT_39] [tinyint] NULL,
	[OBYIPT_40] [tinyint] NULL,
	[OBYIPT_41] [tinyint] NULL,
	[OBYIPT_42] [tinyint] NULL,
	[OBYIPT_43] [tinyint] NULL,
	[OBYIPT_44] [tinyint] NULL,
	[OBYIPT_45] [tinyint] NULL,
	[OBYIPT_46] [tinyint] NULL,
	[OBYIPT_47] [tinyint] NULL,
	[OBYIPT_48] [tinyint] NULL,
	[OBYIPT_49] [tinyint] NULL,
	[FLGVAT_0] [tinyint] NULL,
	[VATIPT_0] [tinyint] NULL,
	[VAT_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VAT_1] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VAT_2] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ESDTRK_0] [tinyint] NULL,
	[SNSDEF_0] [tinyint] NULL,
	[SNSBLC_0] [tinyint] NULL,
	[MTC_0] [tinyint] NULL,
	[CEN_0] [tinyint] NULL,
	[DIFFLG_0] [tinyint] NULL,
	[DIF_0] [tinyint] NULL,
	[LOSGAIGNR_0] [tinyint] NULL,
	[DAS_0] [tinyint] NULL,
	[DASTYP_0] [tinyint] NULL,
	[FLGABL_0] [tinyint] NULL,
	[FLGEXPCRE_0] [tinyint] NULL,
	[FLGDEP_0] [smallint] NULL,
	[GACPVS_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GACACN_0] [tinyint] NULL,
	[RITTYP_0] [smallint] NULL,
	[UPDBLC_0] [tinyint] NULL,
	[AUZBPR_0] [tinyint] NULL,
	[AUZBPR_1] [tinyint] NULL,
	[AUZBPR_2] [tinyint] NULL,
	[AUZBPR_3] [tinyint] NULL,
	[AUZBPR_4] [tinyint] NULL,
	[AUZBPR_5] [tinyint] NULL,
	[AUZBPR_6] [tinyint] NULL,
	[AUZBPR_7] [tinyint] NULL,
	[AUZBPR_8] [tinyint] NULL,
	[AUZBPR_9] [tinyint] NULL,
	[DSP_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DACDIENBR_0] [smallint] NULL,
	[DIE_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_1] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_2] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_3] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_4] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_5] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_6] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_7] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_8] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_9] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_10] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_11] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_12] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_13] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_14] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_15] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_16] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_17] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_18] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_19] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_1] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_2] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_3] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_4] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_5] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_6] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_7] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_8] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_9] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_10] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_11] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_12] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_13] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_14] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_15] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_16] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_17] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_18] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CCEDEF_19] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BUDTRK_0] [tinyint] NULL,
	[TIMDSP_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FRWCUR_0] [tinyint] NULL,
	[BIDNUM_0] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BPAADD_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDDAT_0] [datetime] NULL,
	[CREDAT_0] [datetime] NULL,
	[UPDTIM_0] [int] NULL,
	[CRETIM_0] [int] NULL,
	[UPDUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CREUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXPNUM_0] [int] NULL,
	[CREDATTIM_0] [datetime] NULL,
	[UPDDATTIM_0] [datetime] NULL,
	[AUUID_0] [binary](16) NULL,
	[FLG281_0] [smallint] NULL,
	[TYP281_0] [smallint] NULL,
	[LVATYP_0] [tinyint] NULL,
	[TYPRATFLG_0] [tinyint] NULL,
	[TYPRAT_0] [tinyint] NULL,
	[CNVACC1_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CNVACC2_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CNVACC3_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CNVACC4_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CSLFLGBPR_0] [smallint] NULL,
	[CSLBPRACE_0] [smallint] NULL,
	[CNVACC5_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CNVACC6_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CNVACC7_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CNVACC8_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CNVACC9_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CNVACC10_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPVATCTL_0] [tinyint] NULL,
	[ROWID] [numeric](38, 0) NULL
) ON [PRIMARY]

GO
