SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [PROD1].[CACCE](
	[UPDTICK_0] [int] NULL,
	[CCE_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIE_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DES_0] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DESSHO_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENAFLG_0] [tinyint] NULL,
	[ACS_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FCY_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VLYSTR_0] [datetime] NULL,
	[VLYEND_0] [datetime] NULL,
	[AUZ_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIENBR_0] [smallint] NULL,
	[OTHDIE_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHDIE_1] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHDIE_2] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHDIE_3] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHDIE_4] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHDIE_5] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHDIE_6] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHDIE_7] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHDIE_8] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHDIE_9] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHDIE_10] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHDIE_11] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHDIE_12] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHDIE_13] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHDIE_14] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHDIE_15] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHDIE_16] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHDIE_17] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHDIE_18] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OTHDIE_19] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_1] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_2] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_3] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_4] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_5] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_6] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_7] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_8] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_9] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_10] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_11] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_12] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_13] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_14] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_15] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_16] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_17] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_18] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEFCCE_19] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOMNBR_0] [smallint] NULL,
	[UOM_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOM_1] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOM_2] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOM_3] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOM_4] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOM_5] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOM_6] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOM_7] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOM_8] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOM_9] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOM_10] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOM_11] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOM_12] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOM_13] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOM_14] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOM_15] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOM_16] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOM_17] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOM_18] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UOM_19] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QTY_0] [numeric](28, 13) NULL,
	[QTY_1] [numeric](28, 13) NULL,
	[QTY_2] [numeric](28, 13) NULL,
	[QTY_3] [numeric](28, 13) NULL,
	[QTY_4] [numeric](28, 13) NULL,
	[QTY_5] [numeric](28, 13) NULL,
	[QTY_6] [numeric](28, 13) NULL,
	[QTY_7] [numeric](28, 13) NULL,
	[QTY_8] [numeric](28, 13) NULL,
	[QTY_9] [numeric](28, 13) NULL,
	[QTY_10] [numeric](28, 13) NULL,
	[QTY_11] [numeric](28, 13) NULL,
	[QTY_12] [numeric](28, 13) NULL,
	[QTY_13] [numeric](28, 13) NULL,
	[QTY_14] [numeric](28, 13) NULL,
	[QTY_15] [numeric](28, 13) NULL,
	[QTY_16] [numeric](28, 13) NULL,
	[QTY_17] [numeric](28, 13) NULL,
	[QTY_18] [numeric](28, 13) NULL,
	[QTY_19] [numeric](28, 13) NULL,
	[BUDTRK_0] [tinyint] NULL,
	[FRW_0] [tinyint] NULL,
	[IPT_0] [tinyint] NULL,
	[CREUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CREDAT_0] [datetime] NULL,
	[CRETIM_0] [int] NULL,
	[UPDUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDDAT_0] [datetime] NULL,
	[UPDTIM_0] [int] NULL,
	[EXPNUM_0] [int] NULL,
	[CREDATTIM_0] [datetime] NULL,
	[UPDDATTIM_0] [datetime] NULL,
	[AUUID_0] [binary](16) NULL,
	[ROWID] [numeric](38, 0) NULL
) ON [PRIMARY]

GO
