SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [PROD1].[GACCENTRYD](
	[UPDTICK_0] [int] NULL,
	[TYP_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NUM_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LIN_0] [smallint] NULL,
	[LEDTYP_0] [tinyint] NULL,
	[LED_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACCNUM_0] [int] NULL,
	[CHRNUM_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IDTLIN_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPY_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FCYLIN_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACCDAT_0] [datetime] NULL,
	[FIY_0] [smallint] NULL,
	[PER_0] [smallint] NULL,
	[COA_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SAC_0] [nvarchar](24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACC_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BPR_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DSP_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SNS_0] [smallint] NULL,
	[CUR_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AMTCUR_0] [numeric](27, 13) NULL,
	[CURLED_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AMTLED_0] [numeric](27, 13) NULL,
	[AMTFLG_0] [tinyint] NULL,
	[AMTLED1_0] [numeric](27, 13) NULL,
	[UOM_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QTY_0] [numeric](28, 13) NULL,
	[DES_0] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REFINTLIN_0] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OFFACC_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CSLCOD_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CSLFLO_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STT1_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STT2_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STT3_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MTC_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MTCDAT_0] [datetime] NULL,
	[MTCDATMIN_0] [datetime] NULL,
	[MTCDATMAX_0] [datetime] NULL,
	[FLGMTC_0] [tinyint] NULL,
	[FREREF_0] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CHK_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CHKDAT_0] [datetime] NULL,
	[MRK_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TAX_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TAX2_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TAX3_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AMTVAT_0] [numeric](27, 13) NULL,
	[INDEDVAT_0] [numeric](28, 8) NULL,
	[EXPNUM_0] [int] NULL,
	[ACCNUMORI_0] [int] NULL,
	[ACCNUMDOE_0] [smallint] NULL,
	[CAPFLOTYP_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VATRAT_0] [numeric](16, 7) NULL,
	[VATDEDRAT_0] [numeric](16, 7) NULL,
	[CREDATTIM_0] [datetime] NULL,
	[UPDDATTIM_0] [datetime] NULL,
	[AUUID_0] [binary](16) NULL,
	[CREUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CSLBPR_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[YCBACCNUM_0] [int] NULL,
	[PJTLIN_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZEXPE_0] [tinyint] NULL,
	[ROWID] [numeric](38, 0) NULL
) ON [PRIMARY]

GO
