SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [PROD1].[GACCENTRY](
	[UPDTICK_0] [int] NULL,
	[TYP_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NUM_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPY_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FCY_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[JOU_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FIY_0] [smallint] NULL,
	[PER_0] [smallint] NULL,
	[BOLLATO_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ACCDAT_0] [datetime] NULL,
	[ENTDAT_0] [datetime] NULL,
	[VALDAT_0] [datetime] NULL,
	[DUDDAT_0] [datetime] NULL,
	[BANDAT_0] [datetime] NULL,
	[RATDAT_0] [datetime] NULL,
	[CAT_0] [tinyint] NULL,
	[STA_0] [tinyint] NULL,
	[FNLPSTDAT_0] [datetime] NULL,
	[ORIMOD_0] [tinyint] NULL,
	[DACDIA_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FLGDAS_0] [tinyint] NULL,
	[FLGFUP_0] [tinyint] NULL,
	[FLGPAZ_0] [tinyint] NULL,
	[FLGREP_0] [tinyint] NULL,
	[FLGGEN_0] [tinyint] NULL,
	[TYPDUD_0] [tinyint] NULL,
	[BANCIB_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CUR_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TYPRAT_0] [tinyint] NULL,
	[LED_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LED_1] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LED_2] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LED_3] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LED_4] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LED_5] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LED_6] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LED_7] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LED_8] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LED_9] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CURLED_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CURLED_1] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CURLED_2] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CURLED_3] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CURLED_4] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CURLED_5] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CURLED_6] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CURLED_7] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CURLED_8] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CURLED_9] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RATMLT_0] [numeric](21, 10) NULL,
	[RATMLT_1] [numeric](21, 10) NULL,
	[RATMLT_2] [numeric](21, 10) NULL,
	[RATMLT_3] [numeric](21, 10) NULL,
	[RATMLT_4] [numeric](21, 10) NULL,
	[RATMLT_5] [numeric](21, 10) NULL,
	[RATMLT_6] [numeric](21, 10) NULL,
	[RATMLT_7] [numeric](21, 10) NULL,
	[RATMLT_8] [numeric](21, 10) NULL,
	[RATMLT_9] [numeric](21, 10) NULL,
	[RATDIV_0] [numeric](21, 10) NULL,
	[RATDIV_1] [numeric](21, 10) NULL,
	[RATDIV_2] [numeric](21, 10) NULL,
	[RATDIV_3] [numeric](21, 10) NULL,
	[RATDIV_4] [numeric](21, 10) NULL,
	[RATDIV_5] [numeric](21, 10) NULL,
	[RATDIV_6] [numeric](21, 10) NULL,
	[RATDIV_7] [numeric](21, 10) NULL,
	[RATDIV_8] [numeric](21, 10) NULL,
	[RATDIV_9] [numeric](21, 10) NULL,
	[DESVCR_0] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REF_0] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BPRVCR_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BPRDATVCR_0] [datetime] NULL,
	[REFSIM_0] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REFINT_0] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NUMDCL_0] [int] NULL,
	[RVS_0] [tinyint] NULL,
	[RVSDAT_0] [datetime] NULL,
	[RVSORITYP_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RVSORINUM_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXPNUM_0] [int] NULL,
	[CREDAT_0] [datetime] NULL,
	[CREUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDDAT_0] [datetime] NULL,
	[UPDUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORIGIN_0] [tinyint] NULL,
	[CREDATTIM_0] [datetime] NULL,
	[UPDDATTIM_0] [datetime] NULL,
	[AUUID_0] [binary](16) NULL,
	[FNLPSTNUM_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FNLPSTNUM_1] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FNLPSTNUM_2] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FNLPSTNUM_3] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FNLPSTNUM_4] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FNLPSTNUM_5] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FNLPSTNUM_6] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FNLPSTNUM_7] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FNLPSTNUM_8] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FNLPSTNUM_9] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PJT_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ROWID] [numeric](38, 0) NULL
) ON [PRIMARY]

GO
