SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [PROD1].[SORDERP](
	[UPDTICK_0] [int] NULL,
	[SOHNUM_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SOPLIN_0] [int] NULL,
	[SOPSEQ_0] [int] NULL,
	[CPY_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SOHCAT_0] [tinyint] NULL,
	[STRDAT_0] [datetime] NULL,
	[ENDDAT_0] [datetime] NULL,
	[BPCORD_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BPAADD_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CNDNAM_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BPCINV_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STOFCY_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SALFCY_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ITMREF_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ITMDES1_0] [nvarchar](360) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ITMDES_0] [nvarchar](360) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ITMREFBPC_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VACITM_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VACITM_1] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VACITM_2] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REP1_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REP2_0] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REPRAT1_0] [numeric](8, 3) NULL,
	[REPRAT2_0] [numeric](8, 3) NULL,
	[REPCOE_0] [numeric](6, 3) NULL,
	[GROPRI_0] [numeric](19, 5) NULL,
	[PRIREN_0] [smallint] NULL,
	[NETPRI_0] [numeric](19, 5) NULL,
	[NETPRINOT_0] [numeric](19, 5) NULL,
	[NETPRIATI_0] [numeric](19, 5) NULL,
	[PFM_0] [numeric](27, 13) NULL,
	[CPRPRI_0] [numeric](19, 5) NULL,
	[DISCRGVAL1_0] [numeric](19, 5) NULL,
	[DISCRGVAL2_0] [numeric](19, 5) NULL,
	[DISCRGVAL3_0] [numeric](19, 5) NULL,
	[DISCRGVAL4_0] [numeric](28, 8) NULL,
	[DISCRGVAL5_0] [numeric](28, 8) NULL,
	[DISCRGVAL6_0] [numeric](28, 8) NULL,
	[DISCRGVAL7_0] [numeric](28, 8) NULL,
	[DISCRGVAL8_0] [numeric](28, 8) NULL,
	[DISCRGVAL9_0] [numeric](28, 8) NULL,
	[DISCRGREN1_0] [smallint] NULL,
	[DISCRGREN2_0] [smallint] NULL,
	[DISCRGREN3_0] [smallint] NULL,
	[DISCRGREN4_0] [smallint] NULL,
	[DISCRGREN5_0] [smallint] NULL,
	[DISCRGREN6_0] [smallint] NULL,
	[DISCRGREN7_0] [smallint] NULL,
	[DISCRGREN8_0] [smallint] NULL,
	[DISCRGREN9_0] [smallint] NULL,
	[VAT_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VAT_1] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VAT_2] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLCAMT1_0] [numeric](27, 13) NULL,
	[CLCAMT2_0] [numeric](27, 13) NULL,
	[SAU_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[STU_0] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SAUSTUCOE_0] [numeric](18, 7) NULL,
	[TSICOD_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TSICOD_1] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TSICOD_2] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TSICOD_3] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TSICOD_4] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SOQSTA_0] [tinyint] NULL,
	[LINTYP_0] [tinyint] NULL,
	[FOCFLG_0] [tinyint] NULL,
	[ORILIN_0] [int] NULL,
	[SQHNUM_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CONNUM_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SQDLIN_0] [int] NULL,
	[LINREVNUM_0] [smallint] NULL,
	[EXPNUM_0] [int] NULL,
	[SSTCOD_0] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BPCSALPRI_0] [numeric](28, 8) NULL,
	[CREUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CREDAT_0] [datetime] NULL,
	[UPDUSR_0] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UPDDAT_0] [datetime] NULL,
	[CREDATTIM_0] [datetime] NULL,
	[UPDDATTIM_0] [datetime] NULL,
	[AUUID_0] [binary](16) NULL,
	[INVCND_0] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ROWID] [numeric](38, 0) NULL
) ON [PRIMARY]

GO
