SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [DOCUMENTATION].[TableOfContents](
	[TableOfContentsID] [int] IDENTITY(1,1) NOT NULL,
	[TableName] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TableDescription] [varchar](1000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]

GO
