SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [INTEGRATION].[ingress_DimEmployee](
	[EmployeeKey] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EmployeeNumber] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EmployeeFirstName] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EmployeeSurname] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EmployeeBirthdate] [datetime] NULL,
	[EmployeeDisplayName] [nvarchar](104) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[EmployeeEmailAddress] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MobileNumber] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LogonName] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PositionCode] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PositionDescription] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PositionShortDescription] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[StandardJobCode] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[StandardJobDescription] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[StandardJobShortDescription] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DepartmentCode] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DepartmentDescription] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DepartmentShortDescription] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[X3P_GangCode] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[X3P_GangDescription] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[X3P_GangShortDescription] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReportsToPositionCode] [varchar](8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReportsToPositionDescription] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReportingDepartmentCode] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReportingDepartmentDescription] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReportingDepartmentShortDescription] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EmployeeIsContractor] [smallint] NULL,
	[EmployeeEngagementDate] [datetime] NULL,
	[EmployeeDischargeDate] [datetime] NULL,
	[EmployeeLocation] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EmployeeLocationStatus] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastClockTime] [datetime] NULL,
	[EmployeePositionKey] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReportsToEmployeePositionKey] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
