SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [INTEGRATION].[ingress_EmployeeDetail](
	[EmployeeCode] [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Surname] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FirstName] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ID_Number] [nvarchar](13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PassportNumber] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ContractNumber] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[EngagementDate] [datetime] NOT NULL,
	[Title] [varchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Department] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[DepartmentDesc] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Site] [varchar](29) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SiteCode] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Company] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Profile] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ProfileDesc] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VIPDepartment] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[VIP_DepartmentDesc] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DepartmentLong] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PositionCode] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PositionDescription] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CostDepartment] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CostDepartmentDesc] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CostCentre] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CostCentreDesc] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[JobGrade] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[swBreakdown] [tinyint] NULL,
	[SeniorityDate] [datetime] NOT NULL,
	[Gender] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[RaceGroup] [varchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[EmploymentStatus] [varchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Ethnic Group] [varchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Nationality] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[StandardJobCode] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[StandardJobDesc] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HODCode] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[HODDesc] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ManagerCode] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ManagerDesc] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Logon] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Email] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
