SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [INTEGRATION].[DataDistributionBatchData](
	[DataConcat] [varchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[DataDistributionBatchID] [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
