SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [DEF].[DatabaseDefinition](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DatabaseDefinition] [varchar](1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
