SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [DIMENSION].[DateDimension](
	[CalendarDate] [date] NOT NULL,
	[CalendarDateValue]  AS (CONVERT([int],format([CalendarDate],'yyyyMMdd'))),
	[CalendarDateTime]  AS (CONVERT([datetime2](7),[CalendarDate])),
	[DayOfWeek]  AS (CONVERT([varchar](2),case when (datepart(weekday,[CalendarDate])+([config].[GetDayOfWeekIndex]('Sunday')-[config].[GetDayOfWeekIndex]([config].[GetConfigValue]('FirstDayOfWeekName'))))<(1) then (datepart(weekday,[CalendarDate])+([config].[GetDayOfWeekIndex]('Sunday')-[config].[GetDayOfWeekIndex]([config].[GetConfigValue]('FirstDayOfWeekName'))))+(7) else datepart(weekday,[CalendarDate])+([config].[GetDayOfWeekIndex]('Sunday')-[config].[GetDayOfWeekIndex]([config].[GetConfigValue]('FirstDayOfWeekName'))) end)),
	[DayOfWeekValue]  AS (CONVERT([tinyint],case when (datepart(weekday,[CalendarDate])+([config].[GetDayOfWeekIndex]('Sunday')-[config].[GetDayOfWeekIndex]([config].[GetConfigValue]('FirstDayOfWeekName'))))<(1) then (datepart(weekday,[CalendarDate])+([config].[GetDayOfWeekIndex]('Sunday')-[config].[GetDayOfWeekIndex]([config].[GetConfigValue]('FirstDayOfWeekName'))))+(7) else datepart(weekday,[CalendarDate])+([config].[GetDayOfWeekIndex]('Sunday')-[config].[GetDayOfWeekIndex]([config].[GetConfigValue]('FirstDayOfWeekName'))) end)),
	[DayOfWeekName]  AS (CONVERT([varchar](10),format([CalendarDate],[config].[GetConfigValue]('DayOfWeekName_format')))),
	[DayOfWeekNameAbbreviation]  AS (CONVERT([varchar](10),format([CalendarDate],[config].[GetConfigValue]('DayOfWeekAbbreviation_format')))),
	[DayOfMonth]  AS (CONVERT([varchar](2),format([CalendarDate],[config].[GetConfigValue]('DayOfMonth_format')))),
	[DayOfMonthValue]  AS (CONVERT([tinyint],format([CalendarDate],[config].[GetConfigValue]('DayOfMonth_format')))),
	[DayOfQuarter]  AS (CONVERT([varchar](2),format(datediff(day,dateadd(quarter,datediff(quarter,(0),[CalendarDate]),(0)),[CalendarDate])+(1),[config].[GetConfigValue]('DayOfQuarter_format')))),
	[DayOfQuarterValue]  AS (CONVERT([tinyint],format(datediff(day,dateadd(quarter,datediff(quarter,(0),[CalendarDate]),(0)),[CalendarDate])+(1),[config].[GetConfigValue]('DayOfQuarter_format')))),
	[DayOfYear]  AS (CONVERT([varchar](3),format(datepart(dayofyear,[CalendarDate]),[config].[GetConfigValue]('DayOfYear_format')))),
	[DayOfYearValue]  AS (CONVERT([smallint],datepart(dayofyear,[CalendarDate]))),
	[DayOfYearName]  AS (CONVERT([varchar](7),[config].[GetConfigValue]('DayOfYear_prefix')+format(datepart(dayofyear,[CalendarDate]),[config].[GetConfigValue]('DayOfYear_format')))),
	[WeekOfYear]  AS (CONVERT([varchar](2),format(datepart(week,[CalendarDate]),[config].[GetConfigValue]('WeekOfYear_format')))),
	[WeekOfYearValue]  AS (CONVERT([tinyint],format(datepart(week,[CalendarDate]),[config].[GetConfigValue]('WeekOfYear_format')))),
	[WeekOfYearName]  AS (CONVERT([varchar](7),[config].[GetConfigValue]('WeekOfYear_prefix')+format(datepart(week,[CalendarDate]),[config].[GetConfigValue]('WeekOfYear_format')))),
	[WeekOfMonth]  AS (datediff(week,dateadd(month,datediff(month,(0),[CalendarDate]),(0)),[CalendarDate])+(1)),
	[MonthOfYear]  AS (CONVERT([varchar](2),format([CalendarDate],[config].[GetConfigValue]('MonthOfYear_format')))),
	[MonthOfYearValue]  AS (CONVERT([tinyint],datepart(month,[CalendarDate]))),
	[MonthOfYearName]  AS (CONVERT([varchar](10),datename(month,[CalendarDate]))),
	[MonthOfYearAbbreviation]  AS (CONVERT([varchar](3),substring(datename(month,[CalendarDate]),(1),(3)))),
	[QuarterOfYear]  AS (CONVERT([varchar](1),format(datepart(quarter,[CalendarDate]),[config].[GetConfigValue]('QuarterOfYear_format')))),
	[QuarterOfYearValue]  AS (CONVERT([tinyint],datepart(quarter,[CalendarDate]))),
	[QuarterOfYearName]  AS (CONVERT([varchar](10),[config].[GetConfigValue]('QuarterOfYear_prefix')+format(datepart(quarter,[CalendarDate]),[config].[GetConfigValue]('QuarterOfYear_format')))),
	[HalOfYear]  AS (CONVERT([varchar](1),CONVERT([tinyint],ceiling(((1.00)*datepart(quarter,[CalendarDate]))/(2))))),
	[HalfOfYearValue]  AS (CONVERT([tinyint],ceiling(((1.00)*datepart(quarter,[CalendarDate]))/(2)))),
	[HalfOfYearName]  AS (CONVERT([varchar](10),[config].[GetConfigValue]('HalfOfYear_prefix')+CONVERT([varchar](1),CONVERT([tinyint],ceiling(((1.00)*datepart(quarter,[CalendarDate]))/(2)))))),
	[Year]  AS (CONVERT([varchar](4),format([CalendarDate],[config].[GetConfigValue]('CalendarYear_format')))),
	[YearValue]  AS (CONVERT([smallint],format([CalendarDate],[config].[GetConfigValue]('CalendarYear_format')))),
	[YearName]  AS (CONVERT([varchar](9),[config].[GetConfigValue]('CalendarYear_prefix')+format([CalendarDate],[config].[GetConfigValue]('CalendarYear_format')))),
	[WeekStartDate]  AS ((0)),
	[MonthStartDate]  AS (CONVERT([date],dateadd(day,(1),eomonth([CalendarDate],(-1))))),
	[MonthEndDate]  AS (CONVERT([date],eomonth([CalendarDate]))),
	[QuarterStartDate]  AS (CONVERT([date],dateadd(quarter,datediff(quarter,'1900-01-01',[CalendarDate]),'1900-01-01'))),
	[QuarterEndDate]  AS (CONVERT([date],eomonth(dateadd(month,(2),dateadd(quarter,datediff(quarter,'1900-01-01',[CalendarDate]),'1900-01-01'))))),
	[YearStartDate]  AS (CONVERT([date],dateadd(year,datediff(year,(0),[CalendarDate]),(0)))),
	[YearEndDate]  AS (CONVERT([date],dateadd(year,datediff(year,(0),[CalendarDate])+(1),(-1)))),
	[PreviousYear]  AS (CONVERT([smallint],datepart(year,[CalendarDate])-(1))),
	[SameCalendarDatePreviousYear]  AS (CONVERT([date],dateadd(year,(-1),[CalendarDate]))),
	[NextYear]  AS (CONVERT([smallint],datepart(year,[CalendarDate])+(1))),
	[SameCalendarDateNextYear]  AS (CONVERT([date],dateadd(year,(1),[CalendarDate]))),
	[DayOfYearIndex]  AS (CONVERT([int],[config].[GetCalendarIndex]([CalendarDate],'DAY'))),
	[WeekIndex]  AS (CONVERT([int],[config].[GetCalendarIndex]([CalendarDate],'WEEK'))),
	[MonthIndex]  AS (CONVERT([int],[config].[GetCalendarIndex]([CalendarDate],'MONTH'))),
	[QuarterIndex]  AS (CONVERT([int],[config].[GetCalendarIndex]([CalendarDate],'QUARTER'))),
	[YearIndex]  AS (CONVERT([int],[config].[GetCalendarIndex]([CalendarDate],'YEAR'))),
	[YearDayOfYear]  AS (CONVERT([varchar](7),CONVERT([nvarchar](7),datepart(year,[CalendarDate]))+format(datepart(day,[CalendarDate]),'000'))),
	[YearWeekOfYear]  AS (CONVERT([varchar](6),CONVERT([nvarchar](7),datepart(year,[CalendarDate]))+format(datepart(week,[CalendarDate]),'00'))),
	[YearMonthOfYear]  AS (CONVERT([varchar](6),CONVERT([nvarchar](7),datepart(year,[CalendarDate]))+format(datepart(month,[CalendarDate]),'00'))),
	[YearQuarterOfYear]  AS (CONVERT([varchar](6),CONVERT([nvarchar](7),datepart(year,[CalendarDate]))+format(datepart(quarter,[CalendarDate]),'00'))),
	[YearMonthOfYearValue]  AS (CONVERT([int],CONVERT([nvarchar](7),datepart(year,[CalendarDate]))+format(datepart(month,[CalendarDate]),'00'))),
	[IsToday]  AS (CONVERT([bit],case when CONVERT([date],[config].[GetTodayAdjustedDate]())=[CalendarDate] then (1) else (0) end)),
	[IsWeekend]  AS (CONVERT([bit],case when datepart(weekday,[CalendarDate])=(6) OR datepart(weekday,[CalendarDate])=(7) then (1) else (0) end)),
	[IsPublicHoliday]  AS (CONVERT([bit],[REFERENCE].[TestIsPublicHoliday]([CalendarDate]))),
	[IsWorkDay]  AS (CONVERT([bit],case when datepart(weekday,[CalendarDate])<>(6) AND datepart(weekday,[CalendarDate])<>(7) AND [REFERENCE].[TestIsPublicHoliday]([CalendarDate])<>(1) then (1) else (0) end)),
	[IsSchoolHoliday]  AS (CONVERT([bit],[REFERENCE].[TestIsSchoolHoliday]([CalendarDate]))),
	[IsCurrentWeek]  AS (CONVERT([bit],case when datepart(week,[config].[GetTodayAdjustedDate]())=datepart(week,[CalendarDate]) AND datepart(year,[config].[GetTodayAdjustedDate]())=datepart(year,[CalendarDate]) then (1) else (0) end)),
	[IsCurrentCalendarMonth]  AS (CONVERT([bit],case when datepart(month,[config].[GetTodayAdjustedDate]())=datepart(month,[CalendarDate]) AND datepart(year,[config].[GetTodayAdjustedDate]())=datepart(year,[CalendarDate]) then (1) else (0) end)),
	[IsCurrentCalendarQuarter]  AS (CONVERT([bit],case when datepart(quarter,[config].[GetTodayAdjustedDate]())=datepart(quarter,[CalendarDate]) AND datepart(year,[config].[GetTodayAdjustedDate]())=datepart(year,[CalendarDate]) then (1) else (0) end)),
	[IsCurrentCalendarYear]  AS (CONVERT([bit],case when datepart(year,[config].[GetTodayAdjustedDate]())=datepart(year,[CalendarDate]) then (1) else (0) end)),
	[IsInLast7Days]  AS (CONVERT([bit],case when [CalendarDate]>=dateadd(day,(-8),[config].[GetTodayAdjustedDate]()) AND [CalendarDate]<=dateadd(day,(-1),[config].[GetTodayAdjustedDate]()) then (1) else (0) end)),
	[IsInLast7DaysIncludingToday]  AS (CONVERT([bit],case when [CalendarDate]>=dateadd(day,(-8),[config].[GetTodayAdjustedDate]()) AND [CalendarDate]<=[config].[GetTodayAdjustedDate]() then (1) else (0) end)),
	[IsInLast30Days]  AS (CONVERT([bit],case when [CalendarDate]>=dateadd(day,(-31),[config].[GetTodayAdjustedDate]()) AND [CalendarDate]<=dateadd(day,(-1),[config].[GetTodayAdjustedDate]()) then (1) else (0) end)),
	[IsInLast30DaysIncludingToday]  AS (CONVERT([bit],case when [CalendarDate]>=dateadd(day,(-31),[config].[GetTodayAdjustedDate]()) AND [CalendarDate]<=[config].[GetTodayAdjustedDate]() then (1) else (0) end)),
	[IsPastDate]  AS (CONVERT([bit],case when [CalendarDate]<CONVERT([date],[config].[GetTodayAdjustedDate]()) then (1) else (0) end)),
	[IsFutureDate]  AS (CONVERT([bit],case when [CalendarDate]>CONVERT([date],[config].[GetTodayAdjustedDate]()) then (1) else (0) end))
) ON [PRIMARY]

GO
