SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [UTILITY].[VerbHistory](
	[VerbID] [smallint] NOT NULL,
	[VerbCode] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[StartDT] [datetime2](7) NOT NULL,
	[EndDT] [datetime2](7) NOT NULL
) ON [PRIMARY]
WITH
(
DATA_COMPRESSION = PAGE
)

GO
