SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [DIMENSION].[DateDimension2](
	[CalendarDate] [date] NOT NULL,
	[CalendarDateValue] [int] NULL,
	[CalendarDateTime] [datetime2](7) NULL,
	[DayOfWeek] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DayOfWeekValue] [tinyint] NULL,
	[DayOfWeekName] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DayOfWeekNameAbbreviation] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DayOfMonth] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DayOfMonthValue] [tinyint] NULL,
	[DayOfQuarter] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DayOfQuarterValue] [tinyint] NULL,
	[DayOfYear] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DayOfYearValue] [smallint] NULL,
	[DayOfYearName] [varchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WeekOfYear] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WeekOfYearValue] [tinyint] NULL,
	[WeekOfYearName] [varchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WeekOfMonth] [int] NULL,
	[MonthOfYear] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MonthOfYearValue] [tinyint] NULL,
	[MonthOfYearName] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MonthOfYearAbbreviation] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QuarterOfYear] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QuarterOfYearValue] [tinyint] NULL,
	[QuarterOfYearName] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HalOfYear] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HalfOfYearValue] [tinyint] NULL,
	[HalfOfYearName] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Year] [varchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[YearValue] [smallint] NULL,
	[YearName] [varchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WeekStartDate] [int] NOT NULL,
	[MonthStartDate] [date] NULL,
	[MonthEndDate] [date] NULL,
	[QuarterStartDate] [date] NULL,
	[QuarterEndDate] [date] NULL,
	[YearStartDate] [date] NULL,
	[YearEndDate] [date] NULL,
	[PreviousYear] [smallint] NULL,
	[SameCalendarDatePreviousYear] [date] NULL,
	[NextYear] [smallint] NULL,
	[SameCalendarDateNextYear] [date] NULL,
	[DayOfYearIndex] [int] NULL,
	[WeekIndex] [int] NULL,
	[MonthIndex] [int] NULL,
	[QuarterIndex] [int] NULL,
	[YearIndex] [int] NULL,
	[YearDayOfYear] [varchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[YearWeekOfYear] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[YearMonthOfYear] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[YearQuarterOfYear] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[YearMonthOfYearValue] [int] NULL,
	[IsToday] [bit] NULL,
	[IsWeekend] [bit] NULL,
	[IsPublicHoliday] [bit] NULL,
	[IsWorkDay] [bit] NULL,
	[IsSchoolHoliday] [bit] NULL
) ON [PRIMARY]

GO
