DECLARE @SEARCHSTRING VARCHAR(255) SET @SEARCHSTRING = 'HUB_Customer'
/*
I use '_Speedup' for snapshots of the original table/view. These snapshots are then used by other downstream code.
So when looking for dependencies I look for those that are dependent on the snapshots too.
Replace it with '' if you don't need the facility.
*/
DECLARE @SPEEDSTRING VARCHAR(255) SET @SPEEDSTRING = '_Speedup' 
DECLARE @SEARCHSPEED VARCHAR(255) SET @SEARCHSPEED = CONCAT(@SEARCHSTRING,@SPEEDSTRING)
-- SELECT @SEARCHSTRING, @SPEEDSTRING, @SEARCHSPEED -- test string - uncomment to see if that's working well

SELECT DEP1.REFERENCED_ENTITY_NAME AS SEARCH_NAME,
      --  DEP1.REFERENCED_ID AS SEARCH_OBJECTID,
      --  DEP1.REFERENCING_ID AS REQUIRED_BY1,
       OBJ1.NAME AS REQUIRED_BY1_NAME, -- first level dependency
      --  DEP2.REFERENCING_ID AS REQUIRED_BY2,
       OBJ2.NAME AS REQUIRED_BY2_NAME, -- second level dependency
      --  DEP3.REFERENCING_ID AS REQUIRED_BY3,
       OBJ3.NAME AS REQUIRED_BY3_NAME, -- third level dependency
      --  DEP4.REFERENCING_ID AS REQUIRED_BY4,
       OBJ4.NAME AS REQUIRED_BY4_NAME -- fourth level dependency

FROM SYS.SQL_EXPRESSION_DEPENDENCIES -- This is the dependencies table in SQL PDW. Replace with whatever suits your DBMS.
AS DEP1

LEFT JOIN SYS.OBJECTS -- This is the objects table in SQL PDW. Replace with whatever suits your DBMS.
AS OBJ1
ON OBJ1.OBJECT_ID = DEP1.REFERENCING_ID

LEFT JOIN SYS.SQL_EXPRESSION_DEPENDENCIES
AS DEP2
ON OBJ1.NAME = DEP2.REFERENCED_ENTITY_NAME
OR CONCAT(OBJ1.NAME,@SPEEDSTRING) = DEP2.REFERENCED_ENTITY_NAME

LEFT JOIN SYS.OBJECTS
AS OBJ2
ON OBJ2.OBJECT_ID = DEP2.REFERENCING_ID

LEFT JOIN SYS.SQL_EXPRESSION_DEPENDENCIES
AS DEP3
ON OBJ2.NAME = DEP3.REFERENCED_ENTITY_NAME
OR CONCAT(OBJ2.NAME,@SPEEDSTRING) = DEP3.REFERENCED_ENTITY_NAME

LEFT JOIN SYS.OBJECTS
AS OBJ3
ON OBJ3.OBJECT_ID = DEP3.REFERENCING_ID

LEFT JOIN SYS.SQL_EXPRESSION_DEPENDENCIES
AS DEP4
ON OBJ3.NAME = DEP4.REFERENCED_ENTITY_NAME
OR CONCAT(OBJ3.NAME,@SPEEDSTRING) = DEP4.REFERENCED_ENTITY_NAME

LEFT JOIN SYS.OBJECTS
AS OBJ4
ON OBJ4.OBJECT_ID = DEP4.REFERENCING_ID

WHERE DEP1.REFERENCED_ENTITY_NAME LIKE @SEARCHSTRING OR DEP1.REFERENCED_ENTITY_NAME LIKE @SEARCHSPEED
ORDER BY DEP1.REFERENCED_ENTITY_NAME ASC, OBJ1.NAME ASC, OBJ2.NAME ASC, OBJ3.NAME ASC, OBJ4.NAME ASC