USE master;
GO
--#################################################################################################
-- 2016-07-12 11:21:52.215 PARAGONDENTAL\lizaguirre
--#################################################################################################
EXEC [sp_setPurposeXProperty] '[dbo].[CommandExecute]',					'Server:Core procedure in Ola Hollgren Maintenance'
EXEC [sp_setPurposeXProperty] '[dbo].[CommandLog]',						'Server:Core logging table  in Ola Hollgren Maintenance'
EXEC [sp_setPurposeXProperty] '[dbo].[Customers_Random_Upserts]',		'Data:Testing function inserts  random number of rows'
EXEC [sp_setPurposeXProperty] '[dbo].[DatabaseBackup]',					'Server:Core Backup procedure in Ola Hollgren Maintenance'
EXEC [sp_setPurposeXProperty] '[dbo].[DatabaseIntegrityCheck]',			'Server:Core procedure in Ola Hollgren Maintenance'
EXEC [sp_setPurposeXProperty] '[dbo].[DelimitedSplit8K]',				'String Function:split Varchar(8000) on single char'
EXEC [sp_setPurposeXProperty] '[dbo].[DelimitedSplit]',					'String Function:split varchar(max) on any # of chars'
EXEC [sp_setPurposeXProperty] '[dbo].[DQInitDQS_MAIN]',					'Data Quality Services function'
EXEC [sp_setPurposeXProperty] '[dbo].[fcn_FindEasterSunday]',			'Calendar Function: Calculate Easter Sunday '
EXEC [sp_setPurposeXProperty] '[dbo].[FindChanukah]',					'Calendar Function: Calculate Hannakah'
EXEC [sp_setPurposeXProperty] '[dbo].[fn_parsename]',					'String Function:left to right parsename, any length, any char'
EXEC [sp_setPurposeXProperty] '[dbo].[fn_parsenameScalar]',				'String Function:Scalar version of Parsename, left to Right'
EXEC [sp_setPurposeXProperty] '[dbo].[fnGetNthWeekdayOfMonth]',			'Calendar Function:calculate the 1st/sec/3rd etc monday/tues of a given month '
EXEC [sp_setPurposeXProperty] '[dbo].[GetTodaysDeadlocksV5]',			'Server:Gather deadlock info and email'
EXEC [sp_setPurposeXProperty] '[dbo].[IndexOptimize]',					'Server:Core procedure in Ola Hollgren Maintenance'
EXEC [sp_setPurposeXProperty] '[dbo].[monitor_WaitStats]',				'Server:capture wait stats'
EXEC [sp_setPurposeXProperty] '[dbo].[MSreplication_options]',			'Server:Ms replication proc'
EXEC [sp_setPurposeXProperty] '[dbo].[Passover]',						'Calendar Function: calculate passover'
EXEC [sp_setPurposeXProperty] '[dbo].[PatternSplitCM]',					'String Function:split string based on expression'
EXEC [sp_setPurposeXProperty] '[dbo].[ProperCase]',						'String Function:ITVF that proper cases a varchar 255 string'
EXEC [sp_setPurposeXProperty] '[dbo].[RedGateMessages]',				'Lookup Table:table containing redgate backup error messages for reference'
EXEC [sp_setPurposeXProperty] '[dbo].[ServerInventory]',				'Server:DBA Recap of Current Server'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_AddUserToTypicalPermissions]', 'Database: sample function for adding permissions'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_AskBrent]',					'Server: DBA proc which reviews  more practices'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_base64_decode]',               'String Function:decode a base64 string'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_base64_encode]',               'String Function:convert string to base64 string'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_Blitz]',						'Server:DBA proc which reviews best practices'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_BlitzCache]',					'Server:DBA proc which reviews Procedure Cache info'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_BlitzFirst]',					'Server:DBA proc which Reviews first level server settings'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_BlitzIndex]',					'Server:DBA proc which reviews Index statistics'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_BlitzRS]',						'Server:DBA proc which reviews Reporting Services'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_BlitzTrace]',					'Server:Brent Ozar''s Trace best practices'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_colz]',						'Database:returns quoted column names  for inputed table'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_colzu]',						'Database:returns an insert/update model for inputed table'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_count]',						'Database:count of all rows in table, alternatively, for all schemas/tables matching pattern'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_count_indexes]',               'Database:count indexes on specific table, with details'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_count_ProcExec]',              'Database:count executions of specific proc, with details'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_CreateLinkedServerToMySQL]',   'Server:MySQL linked swerver utility'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_CustomCHECKDB]',               'Database:runs checkdb on current database'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_dates]',						'Reminder:echos handy date formats and datediff calculations'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_dbDocumentation]',             'Database:html documentation of current database'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_dbDocumentationPlus]',         'Database:db documentation workspace'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_dbDocumentationV2]',           'Database:db documentation workspace'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_dbDocumentationV3]',           'Database:db documentation workspace'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_dbspaceused2]',                'Server:Space used per database, order by most space free'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_dbspaceused]',					'Server:Space used per database, order by name'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_dto]',							'Database:creates a script for a c# data transfer objectr'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_export_all]',					'Database:scripts all tables and objects'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_export_allobjects]',			'Database:export all DLL definitions'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_export_data]',					'Database:scripts table passed as  INSERT...VALUES'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_export_schema]',				'Database:for a specific schema, scripts all tables and objects'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_failedjobs]',					'Server:reports all failed jobs'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_find]',						'Database:find object names or column names that are LIKE the inputted  value'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_find_definition]',             'Database:finds procedures or jobs that contain the passed string'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_FindAnyDataReferences]',		'Database:based on the FK hierarchy,finds any tables that actually contain the refernece info passed'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_fix_all_orphaned_users]',		'Server:cursor over all databases, fix all orphans'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_fix_orphaned_users]',          'Database:in current database context, fix any orphaned users'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_foreachdb]',					'Server:improved version '
EXEC [sp_setPurposeXProperty] '[dbo].[sp_GetDDL]',						'Database:scripts any object definition  to a varchar(max)'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_GetDDLa]',						'Database:scripts any object definition toa  copy/pasteable resultset'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_GetDDLaV2]',					'Database:scripts any object definition , renamed constraints to a standard pattern'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_globalfind]',					'Server:searches all databases for objects or columns containing the passed string'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_backup]',					'Server:lists backup information'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_backups]',                'Server:lists backup information'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_CheckDB]',                'Server:Last time CheckDB was run successfully, for all databases'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_compression]',            'Database:for a given table produces estiamtes and script to used enterprise row or page  compression'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_cpu]',					'Server:quick info about CPU usage and percentused/idle '
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_directories]',            'Server:registry entries about directory paths for SQL server'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_diskspeed]',              'Server:identifies slow disks/databases'
EXEC [sp_setPurposeXProperty] '[dbo].[Sp_help_duplicateforeignkeys]',   'Database:finds duplicate foreign keys in the current database'
EXEC [sp_setPurposeXProperty] '[dbo].[Sp_help_duplicateindexes]',       'Database:finds duplicate indexes in current database'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_hashbytes]',              'Reminder:reminder and examples of the hashbytes function'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_heaps]',					'Database:identifies all tables with no clustered index, details on forwarded records'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_indexes]',                'Database:scripts indexes, provides lots of informaiton'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_indexstats]',				'Database:reports how often indexes used for table passed'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_logins]',					'Server:scripts out logins for trnasfer'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_me]',						'Server:helpful info about server, database and permissions'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_MissingIndexes]',         'Database:identifies any indexes with zero useage in one of four types'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_MissingIndexes]',			'Database:reports missing indexes'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_parallel]',				'Server:identifies procedure chache items using parallelism'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_patches]',                'Server:checks server version against snapshot of known service packs and Knowledge Base/Cumulative Updates'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_procCache]',				'Server:identifies useage counts by procedure'
EXEC [sp_setPurposeXProperty] '[dbo].[Sp_help_procexec]',               'Database:counts and executionStats for the passed in proc name(or all procs in cache if null)'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_procs]',					'Database:placeholder, currently a crappy implementation'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_references]',				'Database:defaults to show any object that references otehr servers or databases'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_resourceGoverner]',		'Server:identifies resource governer settings'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_revlogin_roles]',			'Server:expanded revloguin, withs erver roles'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_schemabinding]',			'Database:identifies all items that could be schema bound, with a column showing external references that prevent it'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_schemas]',                'Database:identify and script all non built in schemas'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_servicebroker]',			'Database:info on all queues and identifies any that are stuck/offline '
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_shrinktempdb]',			'Server:quick notes to shrink temp to a given size per file'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_ssrsjobs]',				'Server:info on jobs that were created for SSRS'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_statistics]',				'Database:shows statistiics , how much is changed, script to run manually'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_synonyms]',				'Database:lists and scripts all synonyms'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_table]',					'Database:placeholder, currently a crappy implementation'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_tools]',					'Server:lists all userdefined objects in the master database'
EXEC [sp_setPurposeXProperty] '[dbo].[Sp_help_untrustedconstraints]',	'Database:finds any constraints that were disabled and could be re-enabled via CHECK CHECK'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_unusedindexes]',			'Database:finds all indexes with zero to very little use'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_uptime]',					'Server:Displays both Server and SQL Service Uptimes'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_users]',					'Database:Script users and roles'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_hexadecimal]',					'Database:changes string to hex'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_hierarchy]',					'Database:lists all objects in dependancy/FK hierarchy order'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_InvalidObjects]',				'Database:identifies invalid objects due to missing/renamed objects or columns'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_io]',							'Server:identifies slow disks/databases'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_kill]',						'Server:kill all sessions for a given database'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_LastAccessed]',                'Database:for current database, last read and writes'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_LastAccessedDB2]',				'Server:enhanced for all databases, last time read or write, plus database size and potential space saved'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_LastAccessedDB]',				'Server:for all databases, last time read or write'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_LunarPhaseITVF]',				'Calendar Function: Calculate Lunar Phase'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_memused]',						'Server:current memory used info'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_MScleanupmergepublisher]',		''
EXEC [sp_setPurposeXProperty] '[dbo].[sp_MSrepl_startup]',				''
EXEC [sp_setPurposeXProperty] '[dbo].[sp_QuickMonitor]',                'Server:kicks of a monitoring event for x minites'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_QuickPerf01]',					'Server:queries taking longer than 15 seconds'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_QuickPerf02]',					'Server:top 20 slowest adhoc queries'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_QuickPerf03]',					'Server:Classic Wait stats'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_QuickPerf04]',					'Server:Top 20 poorly performaing queries'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_QuickPerf05]',					'Server:Top Cached SPs By Total Worker time (SQL 2008). Worker time relates to CPU cost'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_QuickPerf06]',					'Server:CPU utilization by database '
EXEC [sp_setPurposeXProperty] '[dbo].[sp_QuickPerf07]',					'Server:DMV execution involving heaps/fullscan'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_QuickPerf08]',					'Server:Top 20 missing indexes'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_QuickPerf09]',					'Server:Top 250 most used stored procedures, targets for tuning'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_QuickPerf10]',					'Server:All user tables that are Heaps/No clustered indexes'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_QuickPerf11]',					'Server:Better Wait Stats'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_SchemaDocumentation]',			'Database:html documentation of current database, for specific schema'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_ScriptAnyTrace]',				'Server:scripts the trace related to traceId passed'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_SendFailMail]',                'Server:resend dbmail taht failed since midnight'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_serverinventory]',				'Server:An at a glance Review of the Server''s specifications related to memory and cpu, and Version Properties '
EXEC [sp_setPurposeXProperty] '[dbo].[sp_Sessions]',					'Server:sessions with open transactions'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_set_traceflags]',				'Server:best practice trace flags'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_setMS_DescriptionXProperty]',	'Database:applies extended event property on MS_Description to table object passed'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_setPurposeXProperty]',			'Database:applies extended event property to object passede'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_show]',						'Database:preview table/view: top 100 rows, order by first column'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_snapshot_all]',                'Database:export all DLL definitions into snapshot table'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_spaceused2]',					'Database:spaced used by table, with bigint due to huge sizes'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_sysfind]',						'Database:find system table or column names LIKE the passed parameter'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_tablespace]',					'Database:spaced used by all tables,'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_uglysearch]',					'Database:search all varchar/char data types for the given string. danger: performance killer'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_update_statistics]',			'Database:Calls Ola Hollgren to update stats'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_UpdateStatistics]',			'Database:custom implementation to update stats'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_whodb]',						'Server:finds all connections ordered by database name, alternatively, just the db passed'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_WhoIsActive]',					'Server:connection and performance monitoring'
EXEC [sp_setPurposeXProperty] '[dbo].[SplitStrings_Ordered]',			'String Function:string splitter featuring faster perf'
EXEC [sp_setPurposeXProperty] '[dbo].[StripComments]',					'String Function:pass DDL, returns DDL stripped of comments'
EXEC [sp_setPurposeXProperty] '[dbo].[StripHighASCII_ITVF]',			'String Function:ITVF to strip characters'
EXEC [sp_setPurposeXProperty] '[dbo].[StripNonAlpha_ITVF]',				'String Function:strips numbers whitespace and punctionation, leaving A-Z'
EXEC [sp_setPurposeXProperty] '[dbo].[StripNonAlphaNumeric]',			'String Function:strip characters'
EXEC [sp_setPurposeXProperty] '[dbo].[StripNonAlphaNumeric_ITVF]',      'String Function:ITVF strip characters'
EXEC [sp_setPurposeXProperty] '[dbo].[StripNonNumeric]',                'String Function:strip characters'
EXEC [sp_setPurposeXProperty] '[dbo].[StripNonNumeric_ITVF]',           'String Function:ITVF strip characters'


EXEC [sp_setPurposeXProperty] '[dbo].[TallyCalendar]',					'Calendar Table'
EXEC [sp_setPurposeXProperty] '[dbo].[TishaBAv]',						'Calendar Function: Calculate Jewish Holiday'
EXEC [sp_setPurposeXProperty] '[dbo].[TuBishvat]',						'Calendar Function: Calculate Jewish Holiday'
EXEC [sp_setPurposeXProperty] '[dbo].[vwExtendedEvent_ApplicationErrors]',	'Server:custom view created as a companion to a specific Extended Event'
EXEC [sp_setPurposeXProperty] '[dbo].[vwExtendedEvent_deadlock_tracking]',	'Server:custom view created as a companion to a specific Extended Event'
EXEC [sp_setPurposeXProperty] '[dbo].[YomHaAtzmaut]',					'Calendar Function: Calculate Jewish Holiday'

EXEC [sp_setPurposeXProperty] '[dbo].[ConvertFromBase64]',              'String Function:converts string from base64 to something readable'
EXEC [sp_setPurposeXProperty] '[dbo].[ConvertToBase64]',                'String Function:converts string from something readable to base64 string'
EXEC [sp_setPurposeXProperty] '[dbo].[Get_LocalDateTimeITVF]',          'Calendar Function:date function gets from UTC date with timezone'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_check_constraints]',      'Database:all check constraints'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_checkconstraints]',       'Database:invalid check constraints'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_clear_servicebrokerqueue]','Database:tool to help fix services with poison messages'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_defaultconstraints]',		'Database:lists and scripts out all default constraints'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_foreignkeys]',			'Database:lists and scripts all foreign keys '
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_impliedforeignkeys]',		'Database:finds all columns that have the same name as an existing Primary key, and does nto have a FK relationship.'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_latency]',                'Server:reports on disk latency for each database file'

EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_mail]',					'Server:scripts out database mail settings'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_mytemptables]',           'Server:lists all temp tables in scope of your current session'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_owners]',					'Database:scripts out all user level permissions'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_primarykeys]',            'Database:lists and scripts all primary keys'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_helpTemp]',					'Database:crappy test proc, unkknown function'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_script_databasemail]',         'Server:scripts out database mail settings'
EXEC [sp_setPurposeXProperty] '[dbo].[StripNonAlphaCustom_ITVF]',       'String Function:strips out a lot of data, leaves spaces and real characters'
EXEC [sp_setPurposeXProperty] '[dbo].[vwExtendedEvent_system_health]',  'Server:custom view created as a companion to a specific Extended Event'

EXEC [sp_setPurposeXProperty] '[dbo].[sp_Glenn2005]',					'Server:Glenn Berry''s SQL Diagnostics Suite'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_Glenn2008]',					'Server:Glenn Berry''s SQL Diagnostics Suite'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_Glenn2008R2]',					'Server:Glenn Berry''s SQL Diagnostics Suite'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_Glenn2012]',					'Server:Glenn Berry''s SQL Diagnostics Suite'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_Glenn2014]',					'Server:Glenn Berry''s SQL Diagnostics Suite'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_clr]',					'Server:Detailed Info Current DB Common Language Runtime'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_cms]',					'Server:Central Management Server Info'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_traceflags]',             'Server:Listing of current Trace Flags, plus all known flags for reference'
EXEC [sp_setPurposeXProperty] '[dbo].[vw_CMSServers]',					'Server:Central Manangement Servers'
EXEC [sp_setPurposeXProperty] '[dbo].[vw_CMSGroups]',					'Server:Central Manangement Server Groups'


EXEC [sp_setPurposeXProperty] '[dbo].[vwExtendedEvent_system_health]',  'Server:custom view created as a companion to a specific Extended Event'

EXEC [sp_setPurposeXProperty] '[dbo].[fn_hexadecimal]',					'String Function:varbinary to a varchar representation'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_defaultdatabase]',        'Server: lists default database of all users, script for missing databases which break login '

EXEC [sp_setPurposeXProperty] '[dbo].[IsValidNPI]','String Function:calculates whether the pass string passes the validation check10 logic for National Provider ID'
EXEC [sp_setPurposeXProperty] '[dbo].[ProperCaseScalar]','String Function:Scalar function that returns the ProperCase version of the string passed'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_fix_indexes]','Database: Runs IndexOptimize from Ola Holgren'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_fix_joboperators]','Database: Assigns an operator to notify for jobs with no value'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_fix_ssrsjobs]','Database:Any jobs related to an SSRS database have the description updated to the report name'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_adusers]','Server: REports all AD users and the grousp they inherit access from'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_fragmentation]','Database:Shows fragmentation of all indexes'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_ssrssubscriptions]','Database:LFor aLL SSRS-type databases,lists all Subscriptions and last run date'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_vlfs]','Server:list and provide script to fix large numbers of Virtual Log Files'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_waits]','Server: Quick Review of current wait stats'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_ssis_startup]',''
EXEC [sp_setPurposeXProperty] '[dbo].[sp_who3]','Server: sp_who version'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_whodmv]','Server: sp_who2, but from DMV''s instead OF old internal cursor'
EXEC [sp_setPurposeXProperty] '[dbo].[StripAlphaCustom_ITVF]','String Function:ITVF strip characters'
EXEC [sp_setPurposeXProperty] '[dbo].[Tally]','Tally or Numbers Table'
EXEC [sp_setPurposeXProperty] '[dbo].[vwExtendedEvent_DDLChanges]','Server:custom view created as a companion to a specific Extended Event'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_ssisdberrors]','Server: If the SSISDB db exists, returns latest error that occurred per package in last 5 days'

EXEC [sp_setPurposeXProperty] '[dbo].[sp_fix_ssisdbLogRetention]',''
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_ansi]','Database:Scripts your current ansi settings for scripting'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_diskspace]','Server:Returns total drive size and available space in MB and GB for reference'
EXEC [sp_setPurposeXProperty] '[dbo].[StripReplaceASCII_ITVF]','String Function: Replaces High Ascii chars with their lower ascii equivilents'

EXEC [sp_setPurposeXProperty] '[dbo].[GetNums]','Database: returns a numbers table with values between the @low and @high values passed'
EXEC [sp_setPurposeXProperty] '[dbo].[Nums]','Database: A numbers table'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_alarms_highVLFCount]','Server: Raises an error for databases with a large number of Virtual Log Files due to database growth.'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_currentjobs]','Server:List of All currently running jobs'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_jobs]','Server:List of All jobs and their last execution status, next run date and more'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_patchesV2]','Server:checks server version against snapshot of known service packs and Knowledge Base/Cumulative Updates'
EXEC [sp_setPurposeXProperty] '[dbo].[sp_help_triggers]','Database:Returns list of all triggers and their parent objects.'
EXEC [sp_setPurposeXProperty] '[dbo].[vwExtendedEvent_AlwaysOn_health]','Server:custom view created as a companion to a specific Extended Event'
EXEC [sp_setPurposeXProperty] '[dbo].[vwExtendedEvent_FailedLogins]','Server:custom view created as a companion to a specific Extended Event'
EXEC [sp_setPurposeXProperty] '[dbo].[vwExtendedEvent_hkenginexesession]','Server:custom view created as a companion to a specific Extended Event'
