SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[adf].[_Level]') AND type in (N'U'))
BEGIN
CREATE TABLE [adf].[_Level](
	[LevelId] [int] IDENTITY(0,1) NOT NULL,
 CONSTRAINT [PK_LevelID] PRIMARY KEY CLUSTERED 
(
	[LevelId] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
