SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dm].[DD05Q_Generated_table_for_View_PROD]') AND type in (N'U'))
BEGIN
CREATE TABLE [dm].[DD05Q_Generated_table_for_View_PROD](
	[TABNAME] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FIELDNAME] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PRIMPOS] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FORTABLE] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FORKEY] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CHECKTABLE] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CHECKFIELD] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_DD05T] PRIMARY KEY CLUSTERED 
(
	[TABNAME] ASC,
	[FIELDNAME] ASC,
	[PRIMPOS] ASC,
	[FORTABLE] ASC,
	[FORKEY] ASC,
	[CHECKTABLE] ASC,
	[CHECKFIELD] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
