SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[ASSET_HIERARCHY](
	[ID] [int] NOT NULL,
	[DIVISION] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[REGION] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ASSET_GROUP] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ASSET_TEAM] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]

GO
