SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[WELL_DOWNTIME](
	[WELL_ID] [int] NOT NULL,
	[DTE] [datetime2](7) NOT NULL,
	[REASON_CODE] [int] NOT NULL,
	[HOURS] [int] NOT NULL
) ON [PRIMARY]

GO
