SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SEC_USER_EXCEPTIONS](
	[USERID] [varchar](64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HIERARCHY_NODE] [varchar](64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HIERARCHY_VALUE] [varchar](64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
