SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SEC_ORG_USER_BASE](
	[EMPLID] [int] NOT NULL,
	[USERID] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IS_EMPLOYEE] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORG_UNIT_ID] [int] NULL,
	[ORG_UNIT_NAME] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MGRID] [int] NULL
) ON [PRIMARY]

GO
