SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[WELL_DAILY_PROD](
	[WELL_ID] [int] NOT NULL,
	[DTE] [datetime2](7) NOT NULL,
	[OIL] [float] NULL,
	[GAS] [float] NULL,
	[NGL] [float] NULL
) ON [PRIMARY]

GO
