SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[SEC_ORG_USER_BASE_MAP](
	[EMPLID] [int] NOT NULL,
	[USERID] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IS_EMPLOYEE] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORG_UNIT_ID] [int] NULL,
	[ORG_UNIT_NAME] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LVL] [int] NULL,
	[SECURITY_CLEARANCE] [varchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORG_UNIT_ID_PATH] [varchar](4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ORG_UNIT_NAME_PATH] [varchar](4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]

GO
