SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[WELL_MASTER](
	[WELL_ID] [int] NOT NULL,
	[WELL_NAME] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DIVISION] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REGION] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ASSET_GROUP] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ASSET_TEAM] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PROD_YEAR] [varchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TVD] [float] NULL
) ON [PRIMARY]

GO
