SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON

CREATE   PROCEDURE [UTILITY].CreateNumbersTable
		@FirstNumber INT = 1
	,	@LastNumber  INT = 1000
AS

BEGIN

DROP TABLE IF EXISTS [UTILITY].Numbers

CREATE TABLE [UTILITY].Numbers(n BIGINT)

;WITH e1(n) AS
(
	SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL 
	SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL 
	SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1 UNION ALL SELECT 1
)														-- 10
	,e2(n) AS (SELECT 1 FROM e1 CROSS JOIN e1 AS b)		-- 10*10
	,e3(n) AS (SELECT 1 FROM e1 CROSS JOIN e2 AS c)		-- 10*100
	,e4(n) AS (SELECT 1 FROM e1 CROSS JOIN e3 AS d)		-- 10*1000
	,e5(n) AS (SELECT 1 FROM e1 CROSS JOIN e4 AS e)		-- 10*10000
	,e6(n) AS (SELECT 1 FROM e1 CROSS JOIN e5 AS e)		-- 10*100000
INSERT  INTO 
	[UTILITY].Numbers(n)
SELECT 
	n = ROW_NUMBER() OVER (ORDER BY n) 
FROM 
	e6 
WHERE
	n BETWEEN @FirstNumber AND @LastNumber
ORDER BY 
	n

CREATE UNIQUE CLUSTERED INDEX 
	ucix_Numbers_n
ON 
	dbo.Numbers(n) 
WITH 
	(DATA_COMPRESSION = PAGE);

END

GO
